### ISSUE TITLE
Crash on startup, node version issue

### ISSUE THREAD

**Issue by piccolbo** [thumbsup/thumbsup#105]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.3.1
Node version: 10.4.0
NPM version: 6.1.0
Operating system: OS X high sierra
```

- Are you getting an error message?

/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/database.js:4:40)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)

- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?

 No difference.
- Is the behavior different from expected?
You bet, it's a crash
- Can you provide steps to reproduce the issue?
enter `thumbsub  --config thumbsup.json`

The config detail may not matter. It worked just fine until I upgraded node.

**Comment by rprieto** [comment]
Hi @piccolbo. If you upgrade node, you will need to rebuild thumbsup using `npm rebuild -g thumbsup` (or alternatively: `npm install -g thumbsup`). I think this affects any package with native extensions since extensions are compiled for a specific Node version.

I'll add a mention in the docs!

**Comment by piccolbo** [comment]
I actually tried that and it doesn't change the outcome.  I also tried `npm rebuild -g thumbsup  --update-binary` per some SO threads. I should have mentioned it sorry.

**Comment by piccolbo** [comment]
I also tried to uninstall and reinstall thumbsup, always with -g option.

**Comment by rprieto** [comment]
Can you try deleting `/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3`, or even `/usr/local/lib/node_modules/thumbsup`?

**Comment by piccolbo** [comment]
Sorry, I have to take back the last assertion, I uninstalled and reinstalled again and the problem is now resolved. Most likely operator error at some point. Thanks.

**Comment by rprieto** [comment]
No problem, glad it's solved! :+1:
