### ISSUE TITLE
Invalid filenames lead to all files being ignored

### ISSUE THREAD

**Issue by tribut** [thumbsup/thumbsup#106]
So I finally found time to sprinkle debug messages across the code hoping to find out why my large gallery was not being generated:

~~~
Differences between disk and index { unchanged: 0, added: 0,  modified: 0, deleted: 0, total: 0 }
~~~

Turns out, the problem is with the error handling in https://github.com/thumbsup/thumbsup/blob/81ee517062c9b6a8623d4c58c5a732646fb72115/src/components/index/glob.js#L21

When a filename is not valid utf-8, this will trigger `ENOENT`. The check silently eats this error, leading to the whole source directory being treated as empty. To reproduce, create a file like

~~~
touch $(echo -e 'breaker_of_galleries\0374.jpg')
~~~

somewhere in the source folder.

I'm not entirely sure why that check for `ENOENT` is there but if it tries to catch a non-existent source directory, an additional check for the value of `err.path` seems to be in order :)

Only took me half a year, but gallery generation is finally working again :smile:  :tada:

**Comment by rprieto** [comment]
Wow that was a very good catch, thanks. Funnily (or not :smile:), this `isEnoentCodeError` code is one of the few areas that doesn't have unit tests!

Thanks for the PR, I'll close this issue.
