### ISSUE TITLE
Debian Jessie install fails?

### ISSUE THREAD

**Issue by ComputerSmiths** [thumbsup/thumbsup#112]
## Bug report

Installing via npm, I get:

npm install -g thumbsup
npm ERR! not a package /tmp/npm-24579-PB_eAJuc/github.com/thumbsup/listr-work-queue.git
npm ERR! Error: ENOENT, open '/tmp/npm-24579-PB_eAJuc/github.com/thumbsup/listr-work-queue.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "thumbsup"
npm ERR! cwd /root
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-24579-PB_eAJuc/github.com/thumbsup/listr-work-queue.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

This is on two different Debian Jessie machines, after:

apt-get update
apt-get upgrade
apt-get install node
apt-get install exiftool
apt-get install graphicsmagick
apt-get install npm
npm install -g thumbsup

About the bug...
Also:
ls -lahR /tmp/npm-22119-wMtHA9Sf/github.com/
/tmp/npm-22119-wMtHA9Sf/github.com/:
total 28K
drwxr-xr-x 3 root root 4.0K Jun 24 08:07 thumbsup

/tmp/npm-22119-wMtHA9Sf/github.com/thumbsup:
-rw-r--r-- 1 root root  62K Jun 24 07:53 listr-work-queue.git
drwxr-xr-x 2 root root 4.0K Jun 24 07:53 listr-work-queue.git-unpack

/tmp/npm-22119-wMtHA9Sf/github.com/thumbsup/listr-work-queue.git-unpack:
-rw-r--r-- 1 root root  62K Jun 24 07:53 index.js

[listr-work-queue.git.zip](https://github.com/thumbsup/thumbsup/files/2130735/listr-work-queue.git.zip)

[index.js.zip](https://github.com/thumbsup/thumbsup/files/2130736/index.js.zip)

**Comment by ComputerSmiths** [comment]
Same thing on Raspberry Pi 3, running this script:
root@hddrpi3:~# cat installThumbsUp
apt-get update
apt-get -y upgrade
apt-get -y install npm
apt-get -y install node
apt-get -y install exiftool
apt-get -y install graphicsmagick
LZZ_COMPAT=1 npm install -g thumbsup

npm ERR! not a package /tmp/npm-29186-qevmqp8f/github.com/thumbsup/listr-work-queue.git
npm ERR! Error: ENOENT, open '/tmp/npm-29186-qevmqp8f/github.com/thumbsup/listr-work-queue.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.35-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "thumbsup"
npm ERR! cwd /root
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-29186-qevmqp8f/github.com/thumbsup/listr-work-queue.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by ComputerSmiths** [comment]
Both those error messages reported:
/*
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
*/
and I've confirmed those with nodejs --version and npm --version.

I can't seem to parse the version numbering scheme for those, if they are not up to date, what's the best method for updating them?

Thanks!

**Comment by rprieto** [comment]
Sorry I missed the info earlier! These are very old versions (end of life a few years ago). I'm surprised that `apt-get` is still getting these.

Can you try following http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/, for example:

```bash
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by ComputerSmiths** [comment]
That gets a lot of warnings about how:
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/thumbsup/node_modules/integer/.node-gyp/10.5.0"

<--- Last few GCs --->

[24131:0x343d798]  2534886 ms: Mark-sweep 631.3 (731.1) -> 624.3 (731.1) MB, 7951.5 / 0.1 ms  (average mu = 0.283, current mu = 0.200) allocation failure scavenge might not succeed
[24131:0x343d798]  2543546 ms: Mark-sweep 631.7 (731.1) -> 624.7 (731.1) MB, 6012.7 / 0.0 ms  (average mu = 0.294, current mu = 0.306) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x586061dc]
    1: StubFrame [pc: 0x58617154]
Security context: 0x28312715 <JSObject>
    2: normalizeString(aka normalizeString) [0x49216a45] [path.js:~57] [pc=0x44755e24](this=0x3f104185 <undefined>,path=0x5270d2f1 <String[62]: /usr/lib/node_modules/npm/node_modules/node-gyp/lib/./install/>,allowAboveRoot=0x3f10422d <false>,separator=0x2835cd65 <String[1]: />,isPathSeparator=0x49216a65 <JSFunction isPosixPathSepara...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
npm WARN listr-work-queue@1.0.0 requires a peer of listr@^0.13.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-03T19_44_43_612Z-debug.log

[2018-07-03T19_44_43_612Z-debug.log]

(https://github.com/thumbsup/thumbsup/files/2161297/2018-07-03T19_44_43_612Z-debug.log)

I'll try it on some of my other machines...

**Comment by ComputerSmiths** [comment]
Ditto on the 'big' (non-RPi) machine with 32G of RAM, so it's unlikely to be RAM...:
[2018-07-03T22_52_01_906Z-debug.log](https://github.com/thumbsup/thumbsup/files/2161315/2018-07-03T22_52_01_906Z-debug.log)

**Comment by rprieto** [comment]
Thanks for the detail, I’ll look into it. There’s other people running on RPi so it must be a specific edge case - maybe due to the unusual message about root access?

Otherwise
- I’ve been thinking about publishing thumbsup as a static binary too, it might help for people who don’t have Node installed
- Do you have Docker installed on your RPi? If so you can use: https://thumbsup.github.io/docs/2-installation/docker/

**Comment by rprieto** [comment]
In case you are still stuck, could you try running the following?

```bash
mkdir tmp && cd tmp
npm init -y
npm install integer
```

In the log you posted it looks like the `integer` package is failing to install. I'd like to see if it works by itself.

**Comment by tiagovaz** [comment]
Hi, I've got a similar issue when trying to install it in a Debian Sid box:

962 verbose about to build /usr/local/lib/node_modules/thumbsup
963 verbose lib/node_modules/thumbsup unbuild
964 info preuninstall thumbsup@2.4.1
965 info uninstall thumbsup@2.4.1
966 verbose true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild thumbsup@2.4.1
967 verbose /usr/local/bin,[object Object] binRoot
968 info postuninstall thumbsup@2.4.1
969 error Error: Method Not Allowed
969 error     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
969 error     at /usr/share/npm/lib/cache/add-named.js:203:12
969 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
969 error     at FSReqWrap.oncomplete (fs.js:135:15)
970 error If you need help, you may report this *entire* log,
970 error including the npm and node versions, at:
970 error     <http://github.com/npm/npm/issues>
971 error System Linux 4.14.0-3-amd64
972 error command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "thumbsup"
973 error cwd /home/tiago
974 error node -v v8.11.2
975 error npm -v 1.4.21
976 error code E405
977 verbose exit [ 1, true ]

**Comment by rprieto** [comment]
Hi, it seems to be due to an old version of npm.

I see you have a recent Node (`8.11.2`) but a very old npm (`1.4.21`, July 2014, current version is `6.x.x`). How did you install them? 

You should be able to upgrade with `npm i -g npm`.

**Comment by tiagovaz** [comment]
Hi @rprieto, yep, that was too old. Installed via apt. As I said, after updating from nodesource I got it properly installed. However I'm having a new issue when trying to create a simple gallery:

thumbsup --input ./photos --output ./gallery

/usr/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/compiled/10.7.0/linux/x64/better_sqlite3.node
    at bindings (/usr/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/database.js:4:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/better-sqlite3/index.js:2:18)

Do you want me to report it as a new issue?

npm 6.1.0
node v10.7.0

**Comment by rprieto** [comment]
Sorry I had missed your second message. For now let's keep this issue as one. If you upgraded, can you try running `cd /usr/lib/node_modules/thumbsup && npm rebuild`?

Sorry for the less-than-ideal experience on Debian. Once we've figured out a few things it would be good to add an FAQ on the website (http://thumbsup.github.io/) for common build problems.

**Comment by tiagovaz** [comment]
@rprieto, I've just built it using your suggestion, thanks. However I had to use the **--unsafe-perm** parameter. Everything is working now. In summary, my recipe was:

`sudo apt install curl software-properties-common`
 curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -`
`sudo apt install nodejs graphicsmagick`
`cd /usr/lib/node_modules/thumbsup && npm rebuild --unsafe-perm`

**Comment by rprieto** [comment]
Thanks @tiagovaz, I have updated the docs at https://thumbsup.github.io/docs/2-installation/npm/ with your workaround.

@ComputerSmiths I'm sorry I don't have any other ideas right now, given that `npm install integer` is also failing. If Docker is available on your Raspberry PI, running the Docker image might be a simpler option.

**Comment by rprieto** [comment]
I'm closing this issue as it's been a while, and it mentions a few different problems (some of which are solved). I hope you solved the rest, but otherwise please re-open an issue with the specifics.
