### ISSUE TITLE
Issue #75 not fixed in docker latest

### ISSUE THREAD

**Issue by oliverdain** [thumbsup/thumbsup#114]
## Bug report

If running as a Docker container:

```
Thumbsup image tag: latest
Docker version: 18.03.1-ce
Operating system: Debian stretch
```

About the bug...

- Are you getting an error message?

Yes, it appears to be exactly the issue described in #75 

```
✔ Indexing folder
 ❯ Processing media (4990/30569)
   ⠋ media/large/2007-04-14-JacobBarMitzvah/LisasPics/IMG_4804.JPG
   ⠋ media/large/2007-04-14-JacobBarMitzvah/LisasPics/IMG_4805.JPG
   ⠋ media/large/Kiko-Pics/VID_20171201_111703.mp4
   ✖ media/thumbs/2007-04-14-JacobBarMitzvah/LisasPics/IMG_4805.JPG
     → Error: Error: Command failed: gm convert: Corrupt JPEG data: premature end of data segment (/input/2007-04-14-JacobBarMitzvah/LisasPics/IMG_4805.JPG).
   Creating website

Unexpected error Error: Error: Error: Command failed: gm convert: Corrupt JPEG data: premature end of data segment (/input/2007-04-14-JacobBarMitzvah/LisasPics/IMG_4805.JPG).

    at job.task.then.catch.err (/thumbsup/node_modules/listr-work-queue/lib/index.js:50:14)
    at <anonymous>
```

- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?

No. The image *is* corrupt so I know why `gm` is failing there. but as per #75 it shouldn't cause the whole gallery generation to fail.

I looks like #75 was closed on June 9 and the Docker image was last updated on June 6 so it *just* missed getting the good-ness.

**Comment by oliverdain** [comment]
I pulled the repo and tried to build the container myself but it fails:

```
Step 8/8 : RUN scripts/cibuild
 ---> Running in cfffeb38a889
Run unit tests

> thumbsup@2.4.0 test /app
> npm run lint && npm run unit


> thumbsup@2.4.0 lint /app
> standard && require-lint

[require-lint] OK

> thumbsup@2.4.0 unit /app
> istanbul cover node_modules/mocha/bin/_mocha

=============================================================================
Writing coverage object [/app/coverage/coverage.json]
Writing coverage reports at [/app/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 25.74% ( 139/540 )
Branches     : 0% ( 0/172 )
Functions    : 0% ( 0/65 )
Lines        : 27.04% ( 139/514 )
================================================================================
module.js:538
    throw err;
    ^

Error: Cannot find module 'listr-work-queue'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)

... etc
```

**Comment by rprieto** [comment]
Thanks for the report. I just fixed the `list-work-queue` issue, if you want to try again.

That's also a good point that the Docker build is not up to date :+1: I'll let you know as soon as it points to the latest version.

**Comment by rprieto** [comment]
The issue was with https://github.com/thumbsup/listr-work-queue, where the wrong commit went to `master`. Can you try cleaning your intermediate Docker layers, as the `npm install` layer might still be in cache?

**Comment by oliverdain** [comment]
Yup, clearing the cache worked and the container built. However, the old instructions to `docker run thumbsupgallery/thumbsup thumbsup` no longer work. You get:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"thumbsup\": executable file not found in $PATH": unknown.
```

It seems there is no longer a `thumbsup` executable created. However, `docker run thumbsupgallery/thumbsup node bin/thumbsup.js` does work.

**Comment by rprieto** [comment]
Hi @oliverdain, I updated Travis so the Docker image is published automatically. Version `2.4.1` should be out soon!

**Comment by oliverdain** [comment]
Excellent! Thanks.

**Comment by oliverdain** [comment]
@rprieto it does not appear to have published any docker images since 2.2.1: https://hub.docker.com/r/thumbsupgallery/thumbsup/tags/. Looking at your build (e.g. https://travis-ci.org/thumbsup/thumbsup/jobs/406461232) it appears that you only push to docker when the commit has been tagged. However, looking at your repo it looks like you haven't tagged anything with 2.4.1 yet: https://github.com/thumbsup/thumbsup/releases

**Comment by oliverdain** [comment]
I tried to build the container myself but it appears that the `Dockerfile.release` pulls thumbsup from npm first. Since I can't push to npm on your behalf I also can't build a container.  It seems to me that it's a bit strange to pull your own code from npm in your `Dockerfile` for a few reasons:

1. Only you can build containers from the code in your repo since the code must first be pushed to npm
2. You have a race condition in your Travis build. You push to npm first but I don't think npm guarantees immediate consistency. Given the popularity of the serivce I'd imagine they use some combination of of CDNs, multiple data centers in multiple locations, a database cluster with multiple read replicas, etc. which means that if you push to npm and then immediately try to read that info you may not be guaranteed to find it.

I'm not sure if point (2) above is true, it's just a guess. But it does seem like a bummer that I can't check our your code and build a container from it myself.

**Comment by rprieto** [comment]
Hi, yes you're right that's the current process. It will publish a new image as soon as I tag version 2.4.1.

I see what you mean about the fact it pulls from npm. The main upside is that it guarantees that the npm/Docker versions are identical. Effectively the Docker image is "the npm package + all the runtime dependencies". Otherwise we'd need a smart Dockerfile that known only to install production dependencies, ignore particular files from publishing, etc.

Building an image manually for testing purposes should be straightforward. You can create a dockerfile similar to (pseudo-code, not tested)

```dockerfile
FROM thumbsupgallery/build:alpine
WORKDIR /thumbsup
COPY .
RUN npm install 
CMD ["node", "bin/thumbsup.js"]
```

Maybe I could include a similar file as `Dockerfile.local` in the repo?

Good point about the race condition. If this appears to be a problem, we can revisit the solution.
