### ISSUE TITLE
Serving original images / no rescale

### ISSUE THREAD

**Issue by rvansa** [thumbsup/thumbsup#115]
## Feature request

Currently thumbsup always rescales original images for presentation. This requires non-trivial disk storage.

I'd like to use thumbsup on Banana Pi (Raspberry Pi kind of device) which serves as backup storage, and I'd like to avoid extra disk space used. Thumbnails are probably ok, but I'd like to use symlinks for the slideshow, not only for `--download-photos`.

Ideally, a complete customization for slideshow links would be nice:
```
--large-custom="custom.php?foo=bar&file=%"
```
where `%` would be replaced by a relative path to the ~original file~ symlink (using the UUID notation for security?) to the original file.

I know thumbsup is a static gallery generator (for good!) and all files generated by it would be static; this is just a way out if I find out that serving full-size images is too slow and want do the rescale on-the-fly.

**Comment by rprieto** [comment]
Hi, thanks for the idea! You're right, I really want to preserve the static aspect of thumbsup. At the same time, there’s no reason why `large` and `download` have to be treated differently.

At the moment, the download behaviour is controlled by:

```bash
# download link = symlink to the source image
--download-photos "symlink" 

# download link = URL to an existing image
--download-photos "link" --download-link-prefix "http://gallery.com"
```

Instead, I like your idea of interpolating the file path. So what if we used:

```bash
# download link = URL to an existing image
# with a new syntax to interpolate the file path
--download-photos "link" --download-link "http://gallery.com/$path"
```

This could then be applied to large previews with:

```bash
# large previews = symlink to the original image
--large-photos "symlink"

# large previews = URL to an existing image
# including possibly to a PHP image resizer
--large-photos "link" --large-link "preview.php?source=$path"
```

**Comment by rprieto** [comment]
Can you elaborate about why you're thinking `preview.php?path=<path to symlink inside output folder>` instead of `preview.php?path=<path to original file inside the input folder>`? Is it about filesystem/access rights?

**Comment by rvansa** [comment]
Not really, AFAIK access rights on symlinks don't matter too much. However I've noticed in the demo gallery that the images are renamed to UUID form. I've assumed that you don't want to disclose original file names, or make the paths easy to guess.

In case of linking to original files, if the URL's in the generated file would look like `preview.php?source=/home/rvansa/backup/photos/2018/photo123.jpg` that would unnecessarily disclose my username and part of directory structure on the host. A properly configured webserver wouldn't allow to read symlinks directly, so it's not the case if you use intermediary symlinks. Maybe it's not important but it's no harm to be a bit paranoid on the internetz.

**Comment by rprieto** [comment]
Oh I think that’s because the demo images are actually named like that. Thumbsup doesn’t do anything fancy with the paths/names.

What I had in mind was for `$path` to expand to the relative path from output to input, e.g. `../../photos/IMG_001.jpg`, which is already the default behaviour if you use `—download-photos link`.

Would that work for now? I’ll have a think how hard it would be to both generate a symlink and customise the URL.

**Comment by rprieto** [comment]
Hi @rvsansa, I had a deeper look:

- it’s relatively easily to add the same options for previews as we have for downloads (copy, large, symlink, link). This means you could use `preview=symlink` to create a symlink to the original photo, and point to it.
- it should be possible to change the `link` behaviour to be fully custom, interpolating `$path`for example. In the meantime you can use the `prefix=preview.php?size=900&path=../../`. It will automatically add the original path add the end, relative to the input folder.
- it will be quite hard to *both* generate a symlink and have a custom URL, as these are 2 different options (link/symlink) and would require a much deeper change. It could happen in the future but it’s unlikely to change short term.

Hopefully this helps a little!

**Comment by rvansa** [comment]
Great, thanks for the heads up! Looking forward to see these changes implemented. After all it shouldn't be hard to let thumbsup generate the links and then `sed` the HTML files and replace links to my liking.

I would strongly encourage to put a big warning on the `link` option in documentation: if a script is used this needs to validate that the provided path is within expected directories, otherwise someone could abuse it to leak sensitive info (imagine that next to `~/backup/photos` I have `~/backup/documents` with e.g. tax forms).

**Comment by rvansa** [comment]
@rprieto Hi, do you have an estimate where this is on the roadmap? I've noticed that recently there was a micro release. Or is this rather a 'contributions welcome' one? (I am not a js developer, but could try out).

**Comment by rprieto** [comment]
I'm hoping to look at it in the next week or two. Contributions are always welcome! In this case it touches
- `bin/options.js` to add a new option like `--preview-photos copy|large|symlink|link` (similar to `--download-photos`)
- `src/model/output.js`, to set the corresponding "relationship" flag, like `rel: 'fs:symlink'`.

Let me know if you want to give it a go, or would rather wait.

**Comment by amcolash** [comment]
Any progress on this one? I would love to symlink videos since at the moment bandwidth is not an issue, but transcoding bottlenecks (on a NAS) are very big.

**Comment by rprieto** [comment]
Hi @amcolash and @rvansa! This is now available on master, there will be a new version out soon. It introduces 4 new flags to control how the preview (lightbox) and downloadable media is generated:

```
--photo-preview  [ resize, copy, symlink, link ]
--video-preview  [ resize, copy, symlink, link ]
--photo-download [ resize, copy, symlink, link ]
--video-download [ resize, copy, symlink, link ]
```

You can check the full documentation at: https://thumbsup.github.io/docs/3-configuration/output-settings/
