### ISSUE TITLE
Reduce visual noise in viewer

### ISSUE THREAD

**Issue by piccolbo** [thumbsup/thumbsup#116]
## Feature request / subjectively a bug

Large Images (or any image in a small enough window) are covered by top and bottom bars. Even waiting a few (too many) seconds, when most control elements disappear, a semi transparent bar with the filename is displayed across the bottom of the image (not always reproducible). The slideshow has the same problems, with the addition that 
1. There is no timeout for control elements
2. There is a dark bar at the top that's turning red as time passes, but at a variable speed, a maximally distracting visual element that never disappears for the duration of the slideshow.

To reproduce, any gallery with large images will do. To maximize pain, reduce the window size until the image fills the screen.

### Solutions

Not sure. 

1. Change viewer. To what? Maybe http://photoswipe.com/ minimal mode, but there's  no slideshow. Or https://galleria.io/ great slideshow with corner to corner image. Want.
2. Expose some viewer configuration
3. Pluggable viewers? Is that even possible?
3. None. I am the only person who finds these design elements objectionable. Everyone else is OK with overlapping bars and bright color animations. I am a nice person, I will get the message.
4. None. There is some consensus around this request, but required changes are major, unrealistic, onerous or worse. I will understand.

I'd be happy to help, but my js and css are rudimentary.
 
thumbsup version 2.4.0

**Comment by rprieto** [comment]
Hi, thanks for the idea & details. I agree it would be nice to have a more immersive viewer as an option.

It's good timing, as of a few weeks ago thumbsup supports custom themes. You can have a look at https://github.com/thumbsup/theme-cards to get an idea of how they work. You should be able to fork it and replace the viewer, or even create your own customised theme (your `option 3`).

Note that I haven't checked, it might be possible to get what you want by changing the [LightGallery](https://sachinchoolur.github.io/lightGallery/) options. At the moment a theme can't expose configuration settings, but it would be nice if it did to achieve your `option 2`.

I'm interested to know how you go. When thumbsup started LightGallery was almost the only choice as most lightbox viewers didn't support local videos (i.e. not a YouTube link). It might have changed now. Maybe it's worth starting a Github issue listing all these projects and what they support, to help theme creators (your `option 1`).

**Comment by piccolbo** [comment]
It looks like there are several LightGallery options that address at least some of my concerns. What is the correct mechanism to set them in thumbsup?

**Comment by piccolbo** [comment]
Done, but they don't seem to take effect. Investigating.

**Comment by piccolbo** [comment]
It was just a refresh away. This is a visually clean conf, but progressBar is not responding to conf change

```
<script>
      $(document).ready(function() {
        $("#media").lightGallery({
          thumbnail: false,
          thumbWidth: 80,
          controls: false,
          loop : false,
          download: true,
          counter: false,
          videojs: true,
          slideEndAnimation: false,
          hideBarsDelay: 30,
          progressBar: false
        });
    </script>

```

**Comment by piccolbo** [comment]
Maybe I forgot to refresh. The above configuration does what I want. Should it become a new theme, like classic-minimal?

**Comment by piccolbo** [comment]
Maybe we shouldn't have a proliferation of themes for each little change here or there.

**Comment by rprieto** [comment]
I'm glad it's working!

I think it will be hard to please everyone with a new theme, as people will want slightly different settings. Ideally, a mechanism to configure settings for a theme would be more flexible / less cumbersome.

Let's have a think about what it could look like. Do you mind opening a new issue about that?

For now I'd recommend keeping your changes locally (or on a fork) and you can keep up with the upstream theme changes if any.

**Comment by piccolbo** [comment]
Sounds good!
