### ISSUE TITLE
Invalid SOS parameters for sequential JPEG

### ISSUE THREAD

**Issue by KevinErath** [thumbsup/thumbsup#117]
## Bug report

```
Thumbsup image tag: thumbsupgallery/thumbsup
Docker version: 18.03.1-ce
Operating system: Ubuntu 18.04 LTS
```

All photos made with an Galaxy S8 Phone raise following error. Pictures from other phones like an IPhone doesn't raise the issue:
````
Unexpected error Error: Error: Error: Command failed: gm identify: Invalid SOS parameters for sequential JPEG (/pictures/test.jpg).
gm identify: Request did not return an image.

    at job.task.then.catch.err (/thumbsup/node_modules/listr-work-queue/lib/index.js:50:14)
    at <anonymous>
```` 

I can fix the pictures with running `exiftool`. For example
`exiftool -artist=me test.jpg`

It would be cool if the error could be handled, or at least those defect pictures would be skipped, so processing can continue. You can find some work arounds when googling about the issue. Unfortunately those solutions seems to be php-related.

**Comment by KevinErath** [comment]
Thanks for the hint. I just build my own docker image via your dockerfile.
It skips the errornuous files now.

Here is a sample for a not working file:
![20180713_134256](https://user-images.githubusercontent.com/12991180/43097845-a70747e2-8ebd-11e8-894c-d1c1c11a1f15.jpg)

**Comment by rprieto** [comment]
Thanks,

To sum up for anyone with the same issue, this seems to be a bug in Samsung's handling of panorama images. The generated JPEG images have invalid metadata markers, which also trips up other programs such as Adobe Lightroom ([see forum](https://forums.adobe.com/thread/2131432 )) or the JavaFX library.

This Python should fix the affected photos: https://gist.github.com/bcyrill/e59fda6c7ffe23c7c4b08a990804b269. I think this is out of scope of thumbsup, so I'll close the issue if you're OK with it.

**Comment by rprieto** [comment]
If you want to switch back to the canonical image, version 2.4.1 is now available on DockerHub: `thumbsupgallery/thumbsup:2.4.1`.
