### ISSUE TITLE
Flexibility in viewer configuration

### ISSUE THREAD

**Issue by piccolbo** [thumbsup/thumbsup#119]
## New feature

The lightgallery currently used in thumbsup to view pictures and videos has a large numbers of configuration options documented at https://sachinchoolur.github.io/lightGallery/docs/api.html
The default are not to everyone's liking, see #116. It was suggested in that ticket to open a discussion on  how to expose more viewer configuration. Options:

1. Themes are the current solution. Options are passed to lightGallery in album.hbs, line 33+. It doesn't seem easiest for the end user though.
2. command line and json configuration. One could just map the lightgallery options to thumbsup options, possibly in a separate viewer section for the config and with a viewer- prefix for the cmd line, followed by the lightgallery name. progressBar for instance would be set with --viewer-progressBar false or {"viewer":{"progressBar": false}} Maybe not the prettiest, but I think a manual remapping of gallery options to thumbsup imposes a permanent maintenance burden that's best avoided, unless lightgallery is very stable and we have no plans to ever allow to plug in a different one, like galleria.io. This approach could easily extend to different viewers.

**Comment by oupala** [comment]
## Feature request

In slideshow mode, the timeout before switching to the next photo is not configurable, it's something like 3 seconds.

This timeout should be configurable on the admin side (somewhere on the json config file) but also on the viewer side, with a small way to set this default timeout (never, 1, 3, 5, 10 seconds are good default values).

**Comment by rprieto** [comment]
Hi, I'm tidying up issues. I think this is covered by #137 which is about theme options in general. I'll add a summary of the ideas above over there.
