### ISSUE TITLE
Using docker on server which I don't have sudo access to

### ISSUE THREAD

**Issue by linzhiqiu** [thumbsup/thumbsup#120]
I was trying to use thumbsup using docker on a server which I don't have sudo access to.

When I run the script in the docker tutorial:
```
docker run -t              \
  -v `pwd`:/folder       \
  -u $(id -u):$(id -g)     \
  thumbsupgallery/thumbsup \
  thumbsup --input /folder/input_folder --output /folder/output_folder;

```

I got the below error message:
```
/thumbsup/node_modules/make-dir/index.js:77
				throw err;
				^

Error: EACCES: permission denied, mkdir '/.config'
    at Object.fs.mkdirSync (fs.js:885:18)
    at make (/thumbsup/node_modules/make-dir/index.js:61:12)
    at make (/thumbsup/node_modules/make-dir/index.js:68:5)
    at Function.module.exports.sync (/thumbsup/node_modules/make-dir/index.js:84:9)
    at Conf.get store [as store] (/thumbsup/node_modules/conf/index.js:120:13)
    at new Conf (/thumbsup/node_modules/conf/index.js:44:57)
    at new Insight (/thumbsup/node_modules/insight/lib/index.js:40:35)
    at new Analytics (/thumbsup/node_modules/thumbsup/bin/analytics.js:11:20)
    at Object.<anonymous> (/thumbsup/node_modules/thumbsup/bin/thumbsup.js:29:19)
    at Module._compile (module.js:652:30)

```

I don't have access to execute "mkdir /.config", and I wonder if this is the issue. Is there anything I could do to avoid operations that require sudo access??

Thanks in advance for your help!

**Comment by rprieto** [comment]
Hi, this seems to be a bug in the Docker image itself when running with `-u $(id -u):$(id -g)` (even though that's what the thumbsup docs say). I will look at it soon. In the meantime you can:
- run the container without the `-u` option, but you might have to re-chown the generated files afterwards
- add `--no-usage-stats`, which should remove this error

**Comment by linzhiqiu** [comment]
Thanks! With this flag the permission issue still wasn't solved though - it throws the same permission denied error at another folder (the output folder). Is it because we need the root access to use the docker?

**Comment by rprieto** [comment]
That's odd, no you shouldn't need root access. I'll investigate further. In the meantime can you use it without the `-u` flag?

**Comment by linzhiqiu** [comment]
Yes, I remove the -u flag and use the --no-usage-stats flag in thumbsup command. That doesn't work though.

I actually just installed all the packages locally via my server's administrator, so I am now able to run it without docker. However, there are [still some issues](https://github.com/thumbsup/thumbsup/issues/122). Basically it was not able to read all my images files so that the website it rendered is full of question marks :-(

Let me know if there is anything I could do to help you debug this!

**Comment by linzhiqiu** [comment]
The above issue was solved

**Comment by rprieto** [comment]
Thanks I'm glad you solved the `libjpeg` problem. I'll let you know when I figure out the permission issue.

**Comment by zacheryph** [comment]
This can be fixed by overriding the `HOME` environment variable (while still using -u). It might be useful to document / hardcode this into the Dockerfile so running doesnt care about the uid/gid.

`docker run --rm -it -u "$(id -u):$(id -g)" --env HOME=/tmp .....`

**Comment by rprieto** [comment]
Thanks a lot @zacheryph! I'll update the base Docker image to use your fix.

**Comment by rprieto** [comment]
I checked that the fix works well for me too :+1: Before I push the new image, what do you think is better?

```dockerfile
# simple, everyone has access, but could be messy
# any downsides?
ENV HOME /tmp
```

or

```dockerfile
# more complex, but cleaner
RUN mkdir -p /home/thumbsup
RUN chmod 777 /home/thumbsup
ENV HOME /home/thumbsup
```

**Comment by zacheryph** [comment]
Either way, doesn't matter to me?

When it comes to docker/containers things like this I tend to not put too much effort/thought into.  Anyone running `thumbsup` like me its going to be a fresh container every time and `/tmp` will be empty, and... no longer exist within a minute or two :wink:

**Comment by rprieto** [comment]
Sounds good, just wanted to check before pushing a new image :+1: Will let you know when it's out!
