### ISSUE TITLE
Image annotation

### ISSUE THREAD

**Issue by linzhiqiu** [thumbsup/thumbsup#123]
I am doing a project where I have a label/score associated with each image, and I have been looking for ways to do that. It turns out what thumbsup already has is a great starting point for me since my images are nested in subfolder and there are a ton of them, so thumbsup album is providing me a great visualization. 

Is it possible to add some image annotation in this album - if not I may consider adding this feature to your library. Just let me know how I should proceed with it :-)

**Comment by rprieto** [comment]
Hi, that sounds interesting. What type of annotations are you thinking about? How would they be rendered?

Thumbsup is heavily based on image metadata. Could you store your labels as IPTC `Keywords`, and the score as the XMP `Rating`? Then this data will automatically be available for rendering, and you could create a custom theme to display them however you want (see https://github.com/thumbsup/theme-cards for an example).

**Comment by linzhiqiu** [comment]
This sounds promising! I am actually thinking of annotation like this:
![albums](https://user-images.githubusercontent.com/10042427/44008127-cc40cec4-9e6d-11e8-9b2f-bf3b0481ce22.png)

The only difference is that your annotation is for an album, and I would like to have such an annotation for each image. It will be better if the description could also show up somewhere after I click an image in the album. 

And it will also be nice if I could sort the images in an album using the score stored as XMP `Rating`.

I have little web-developing experience but I guess I could start with the custom theme. Let me know if you have additional tips!

**Comment by rprieto** [comment]
Hi, that sounds like a great idea for a theme. Have a look at https://github.com/thumbsup/theme-cards and you should be able to make a theme that has a similar style previews for all photos.

If you use `--embed-exif` you should also see all the extra data you mentioned (caption, rating) in the "info" side panel of the light box. You can also explore `--album-from` if you want to make albums based on the rating values.

I'll close the issue for now (for tracking purposes) but leave another comment if you're looking for advice.

Don't hesitate to open a new issue for sorting by rating too, it's an interesting idea!
