### ISSUE TITLE
provide a link to download an album as a zip file

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#125]
## Feature request

thumbsup currently provide a link to download each image/video. It could be useful to also provide a link to download a whole album. Imagine a special event (marriage, part) where guests might want to download all images, it would be painful to ask then to download each image one by one.

It could be very very useful if they can download the whole album in one click, *as a **zip** file*.

This should be optional as it could be very very disk consuming. As albums are *virtual*, this could mean generating a lot of zip file, especially as albums could contain sub-albums (folders and sub-folders).

But that would really be useful in some cases.

**Comment by amcolash** [comment]
I am not sure if this might be a better idea, but adding in custom build step in which a user could define their own post-build scripts such as generating zips might be useful for a more extensible (plugin-like) system. With that along with a custom theme, you could essentially have exactly what you were looking for without needing to build this into the platform itself since it seems like the main use-case of this product is for generating many albums instead of a single one.

Take everything that I say with a grain of salt as I am just a user of this code and dev by day.

**Comment by rprieto** [comment]
Hi @oupala and @amcolash. Thanks for feature request. In your use-case @oupala, building ZIP files makes a lot of sense. However I think it would come with a lot of complexity and edge cases for a lot of other people, for example:
- when do we re-generate the ZIP files? On every build? On demand?
- how do we know which files to generate? Re-building every album could be extremely expensive, for example I have 60 albums with about 6000 photos. Do we need to keep track of which files have been added and removed?

I hadn't thought of a plugin system, but I think it would be a great solution. This means you can implement the ZIP file system in a few lines of code, with the process that makes sense to you. @amcolash what did you have in mind? I like your idea of `post-build`, maybe a plugin could have several phases where they can execute code.

**Comment by rprieto** [comment]
I agree that HTML pages and ZIP files are similar for this purpose. The part that's missing above is that

- images are processed on a 1-by-1 basis, whenever they change. It's as easy as checking the thumbnail timestamp against the source timestamp. Albums do not come into play here.
- on the other hand, all HTML pages are re-built *every time* you run thumbsup. It only takes a few milliseconds anyway, and means we don't have to keep track of which albums have been modified.

This is why incremental ZIP building would add a lot of complexity. I also assume that non-incremental ZIP building would be much too expensive for most use cases.

**Comment by rprieto** [comment]
Apologies, I just learnt you can create incremental ZIP files: https://superuser.com/questions/544336/incremental-backup-with-7zip. If we can create/update the ZIP files incrementally I'm happy to add a `--create-zip-albums` flag (or similar).

The example above is for 7Zip. Ideally I'd prefer to use a generic ZIP binary or library. If we can't find anything, then relying on 7Zip would be OK. @oupala are you interested in having a look & implementing it?

**Comment by rprieto** [comment]
Update: this work great on macOS:

```bash
zip -FS album.zip file1 file2 file3
```

`-FS` seems to be a recent but standard flag. Can someone confirm if it works well on major Linux distros? It might be an issue on Windows, we could always add a disclaimer to the docs.

**Comment by rprieto** [comment]
Update: this work great on macOS:

```bash
zip -FS album.zip file1 file2 file3
```

`-FS` seems to be a recent but standard flag. Can someone confirm if it works well on major Linux distros?

So the three options seem to be:
- use the Unix `zip`, but it won't work on Windows unless there's an equivalent to install.
- use 7Zip and make it a soft-dependency (only required if you need to ZIP albums)
- use a JavaScript library like https://www.npmjs.com/package/jszip, and read the ZIP file, figure out what needs to be added/deleted/updated, then update the file.

**Comment by amcolash** [comment]
`-FS` works fine for me on ubuntu 18.04 (looks like I am using zip version 3.0).

**Comment by oupala** [comment]
@rprieto Unfortunately, I'm not skilled enough in js to implement this feature by myself. But I would be a happy tester of this feature.

I'm using debian stretch (stable) and the version of zip available is 3.0-11+b1 so it should be ok. But I think it would be better to rely on a js library so this part of the software is independant from the operating system (and doesn't add some requirements).

**Comment by gautamkrishnar** [comment]
https://archiverjs.com/ will be a good choice. Is anyone working on this feature yet? I would love to take a look into this.

**Comment by rprieto** [comment]
Hi @gautamkrishnar , that's great thanks for offering your help. Does Archiver support updating ZIP files (removing non-existent files, adding new ones, changing updated files)? My preference would be

- to use a JS lib if it's very simple, i.e. just a few lines of code to generate or update each ZIP file
- to use 7zip otherwise, because it adds a dependency but on the other hand it should take < 50 lines of code (easier to maintain)

**Comment by rprieto** [comment]
This is now implemented on `master`, simply add the new `--album-zip-files true` option!
Some notes:

- it only works on Linux / macOS for now because it depends on the `zip` executable. We could add Windows support later if needed by delegating to 7zip, or finding a JS library (as long as it's fast).
- it only ZIPs *direct* files of an album, not files from nested albums. This was done to avoid bigger and bigger zip files as you get close to the root.
- rendering is still left to the themes, who can use logic like:

```hbs
{{#if album.zip}}
  <a href="{{album.zip}}">Download zip file</a>
{{/if}}
```

**Comment by oupala** [comment]
This is a good news!

As far as I understand, the themes that come with thumbsup don't offer the download link yet, right?

**Comment by gautamkrishnar** [comment]
Awesome work @rprieto. Sorry i totally forgot about this issue. Really happy to know that this is now resolved 😄 👍

**Comment by oupala** [comment]
I tested it, and it appears that there is no link to download the album.

There is two options:

- either themes does not yet support album downloading
- or this feature has not yet been release

I tested release 2.9.0 of thumbsup.

By the way, a CHANGELOG file would be welcome to know what feature and bugfix are in which release.

**Comment by rprieto** [comment]
Hi @oupala, you're right none of the themes display the link right now. If you have some ideas, please do open a pull request. Otherwise I'll add them little by little.

Also great idea for the change log!

**Comment by oupala** [comment]
Is the zip file generation included in version 2.9.0? I can't succeed to make it working.

**Comment by rprieto** [comment]
No sorry it will be in 2.10.

**Comment by oupala** [comment]
Ok, that's why I was not finding any zip file.

I'll wait for release 2.10.

**Comment by rprieto** [comment]
Hi @oupala, the new version is out. Themes don't render any links yet, you can use a custom theme in the meantime.

**Comment by oupala** [comment]
I've just tested it, it works well .. when zip executable is installed (on linux).

But if zip is not installed, the error is not very well handled, and hence not very explicit.

> Unexpected error Error creating ZIP file  /path/to/album.zip

Maybe a better error message could be helpful for users.

> Cannot generate zip files, please install `zip` executable.

I'll test it further and see how it can be integrated into currently existing theme (but I'm really not very good at web design).

**Comment by rprieto** [comment]
Hi, the full error message should include

> thumbsup:error Error: please verify that <zip> is installed on your system
> thumbsup:error Error: spawn zip ENOENT

Although it is followed by a big stack trace... so I agree it's easy to miss.

**Comment by oupala** [comment]
In the default log level, the error message is almost cryptic. Here is the full log:

```bash
  ✔ Indexing folder
  ✔ Resizing media
  ✖ Updating ZIP files
    → Error creating ZIP file /path/to/dev-gallery/01_b
…
    Cleaning up
    Creating website


Unexpected error Error creating ZIP file /path/to/dev-gallery/01_gallery-name.zip

┌───────────────────────────────────────────────────────────────────────────┐
│                                                                           │
│  Something went wrong!                                                    │
│                                                                           │
│  An unexpected error occurred and the gallery didn't build successfully.  │
│  This is most likely an edge-case that hasn't been tested before.         │
│                                                                           │
│  Please check thumbsup.log in the output folder.                          │
│  To help improve thumbsup and hopefully resolve your problem,             │
│  you can raise an issue at https://github.com/thumbsup/thumbsup/issues.   │
│                                                                           │
└───────────────────────────────────────────────────────────────────────────┘
```

**Comment by oupala** [comment]
The real cause was that zip was not installed. All went well once I installed the zip package.

It's just that being sure that it was because of the unavailability of the `zip` executable was not obvious.

**Comment by oupala** [comment]
I proposed a change in the theme [theme-classic](/thumbsup/theme-classic), see this [pull request](https://github.com/thumbsup/theme-classic/pull/2).

I'm definetly not a good web designer. Feel free to improve what' I've proposed.
