### ISSUE TITLE
Issues with folders that have quotes in them

### ISSUE THREAD

**Issue by amcolash** [thumbsup/thumbsup#127]
I am using thumbsup (docker + cards theme) and have a few folders with single quotes and noticed that the thumbnail images for said folders do not show up. This is an issue with the generated css for a given image. I am not sure if this is specific to this theme, but the image naming should be consistent across all themes.

I would suggest removing odd characters to try to prevent this issue `' " / \ ? &` etc similarly to the actual urls that get generated. This would ensure that whether a single or double quote is used, there is no issue.

Here is the relevant anchor thumbnail element: `<a href="2017-May-5-13MikesGraduation.html" style="background-image: url('media/large/2017/May/5-13 Mike's Graduation/IMG_5763.jpg')">.....</a>`

Notice I used a single quote in the folder name which then causes these issues. Interestingly, the generated thumbnails for actual images work ok. And use double quotes like this: `<img src="media/thumbs/2017/May/5-13 Mike's Graduation/IMG_5773.jpg" width="120" height="120" alt="IMG_5773.jpg">`

**Comment by amcolash** [comment]
After some investigation, it looks like it is an issue specifically with the cards theme using single quotes in for the css `background-image` url. Added a PR to allow for escaping

**Comment by rprieto** [comment]
Fixed by #145, thanks for your PR!
