### ISSUE TITLE
provide a flag to ignore or process images or videos

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#128]
## Feature request

It would be great to provide a flag to tell thumbsup if we want to process images, videos, or both.

Such as:

```
--process-image=true (default true)
--process-videos=true (default true)
```

This way, we can keep the source directory untouched, and process only the files we want to process.

**Comment by oupala** [comment]
Imagine that we don't have ffmpeg installed, we don't want all videos to be processed whatever their extension is. That's why I think a flag excluding all videos could be useful.

But adding flags that work on extensions is also a good idea, in addition to general flags for videos and photos.

By the way, I can see that thumbsup transcode videos to mp4. Is there a way to configure that? We might prefer webm instead of mp4.

**Comment by rprieto** [comment]
That's sounds good, I'm happy to start with the 3 options for photos / videos / raw photos. If someone wants to implement it I'm happy to take a pull request! That logic is all in one file, and should be easy to unit test.

For the output format, can you open a new issue please?

**Comment by rprieto** [comment]
Hi @oupala, master now has 3 new flags:
- `--include-photos` (default true)
- `--include-videos` (default true)
- `--include-raw-photos` (default false)

**Comment by oupala** [comment]
That's over-great @rprieto, I can not wait to try this!
