### ISSUE TITLE
Support HEIC format

### ISSUE THREAD

**Issue by rprieto** [thumbsup/thumbsup#131]
Photos from iOS are now stored in HEIC files, for example in `/Users/me/Pictures/Photos Library.photoslibrary/Masters`. These can be either plain photos or "live" photos (with a short video). Thumbsup should support HEIC files in the source folder, at least the photo part.

This could be based on https://github.com/monostream/tifig or https://github.com/wshelley/heic-to-jpeg.

**Comment by rprieto** [comment]
Note: ImageMagick has added support for HEIC (https://github.com/ImageMagick/ImageMagick/issues/507), although it would require some work on the thumbsup Alpine-based Docker image.

I didn't see any open issues about it for GraphicsMagick.

**Comment by hcconquer** [comment]
it seem's nobody to follow it.

**Comment by oupala** [comment]
> it seem's nobody to follow it.

What do you mean @hcconquer? No other device maker is using the video format?

**Comment by scubachristopher** [comment]
Apple use the format.  I too ask for HEIC support.

**Comment by jacket** [comment]
+1

**Comment by itsmultani** [comment]
+1

**Comment by rprieto** [comment]
Thanks for the feedback, it's one of the next features on the roadmap! Please use the :+1: button on the initial issue, it makes it easier to track.

**Comment by rprieto** [comment]
The `master` branch now supports HEIC photos. Feel free to try it out, it will be in the next release.

Note: HEIC photos are quite slow to process (several seconds per photo) because they first have to be converted, and the color profile has to be adjusted. It only happens once though, since it's based on timestamps like with all other images.

**Comment by rprieto** [comment]
Version `2.11.0` is now out with HEIC support.
