### ISSUE TITLE
Passing options to themes

### ISSUE THREAD

**Issue by rprieto** [thumbsup/thumbsup#137]
As mentioned in #136, there is no mechanism to provide options to themes.
It could be useful to turn features on/off.

This is a blank issue to start a conversation regarding
- the use cases
- what the syntax / usage could look like

**Comment by thanhtunguet** [comment]
> As mentioned in #136, there is no mechanism to provide options to themes.
> It could be useful to turn features on/off.
> 
> This is a blank issue to start a conversation regarding
> 
> * the use cases
> * what the syntax / usage could look like

I have tried to add comment box to theme "cards" for each image. It looks so cool.
This uses 2 options:
1. Comment box status: on/off
2. Website root URL to be combined to full href parameter for individual image. (This option may be global option, not depend on comment box is on or off).

I think the syntax to implement these options might be like below:
```bash
thumbsub --input /path/to/input --output /path/to/output --theme <theme name> --theme-comment-box on --origin-url https://example.com
```

**Comment by rprieto** [comment]
A use case mentioned in #119 is the ability to pass options to `LightGallery` (currently used in all official themes). This includes:
- slideshow timeout
- showing / hiding the progress bar 

As @piccolbo said maintaining a mapping of every LightGallery option is not realistic, so we ideally need a way to pass arbitrary theme options, which can be passed on to the viewer plugin.

For example:

```bash
--theme "classic"
--theme-style "custom.less"
--theme-options "..."
```

Where `--theme-options" can be
- key/values like `timeout=3` (repeated if needed)
- a JSON string like `{"timeout": 3}`
- a path like `file://options.json`

**Comment by rprieto** [comment]
This is now implemented on master, with `--theme-settings`.
