### ISSUE TITLE
How Should I Implement Friendlier Album Names?

### ISSUE THREAD

**Issue by techxplorer** [thumbsup/thumbsup#142]
Hi,

This isn't a bug report or feature request as such. It's more of a how-to / is this a good idea type of question. 

I understand that the name of an album is derived from the folder name. For example if I have a folder of images called 'gundam' then the album name becomes 'Gundam'.

What I would like to do is have friendlier album names without longer folder names. For example for the folder 'gundam' I'd like the album name to be 'Gundam Models'. 

As I'm working on implementing my own theme, I wondered if this could be dealt with in the hbs template. 

I could maintain a list of album names keyed by folder name. A matching entry in the list would then be used to replace the album name derived from the folder name with a more friendlier version.

As I'm new to the project, and node based applications in general, I wanted to see if this is a good idea, or if there is a better way. 

I understand that album metadata is to be addressed as part of #126 but I thought this could be a good alternative measure. 

Any thoughts will be most gratefully received. 

-Corey

**Comment by rprieto** [comment]
Hi, that's a good question. I don't suggest doing that in the theme, as the theme should've be responsible for rendering. I can see two options:

- wait for album metadata to be implemented. It would be the most flexible, but requires some tech design so it might be a while
- use the [--albums-from custom.js](https://thumbsup.github.io/docs/3-configuration/album-settings/) option and implement your own mapping logic, for example

```js
const path = require('path')
const map = {
  'london': 'London family trip',
  'madrid': 'Madrid holidays 2018'
}
module.exports = file => {
  const folder = path.dirname(file.path)
  const name = map[folder]
  return name || 'Miscellaneous'
}
```

**Comment by techxplorer** [comment]
@rprieto Thanks for your thoughts and considered answer. 

In my spare time I'm going to be working on my theme, and will let you know the outcome.

**Comment by rprieto** [comment]
No problem. There was a typo in the code snippet above so I just edited it.

**Comment by techxplorer** [comment]
Thanks for your help @rprieto and for developing this awesome static gallery generator. 

Over the past week I've developed [my own theme](https://bitbucket.org/techxplorer/txp-thumbsup-theme/) and used it to generate [my new photo gallery site](https://photos.techxplorer.com/).

**Comment by rprieto** [comment]
Hi, I'm glad it all worked. Your theme looks amazing, and very different from any of the built-in themes. If you decide to make it more generic at some point (to be used by anyone) let me know and I'd love to mention it in the official docs with a few screenshots!
