### ISSUE TITLE
Theme override documentation

### ISSUE THREAD

**Issue by piccolbo** [thumbsup/thumbsup#150]
#Feature request

Picking up from thumbsup/theme-cards#4, there is already the possibility to override theme variables in a custom LESS file, but some more docs and theme-specfic docs might be needed, together with examples. Theme-specific docs would list what can be overridden and what the semantics is.

**Comment by rprieto** [comment]
I added some more detail at https://thumbsup.github.io/docs/4-themes/themes/ and https://thumbsup.github.io/docs/4-themes/built-in/. Each theme's repository now also lists the configuration options.
