### ISSUE TITLE
can't use the --log parameter with null value

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#154]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.10.0
Node version: v10.15.3
NPM version: 6.9.0
Operating system: linux
```

About the bug...

I'm trying to use the `--log` parameter. But I want - by default - to use a null value (default value).

- using `--log "null"` makes it "null" (not null):

> Valeurs invalides:
>  Argument: log, Donné: "null", Choix: null, "info", "debug", "trace"

- using `--log null` makes it "null" (not null):

> Valeurs invalides:
>  Argument: log, Donné: "null", Choix: null, "info", "debug", "trace"

- using `--log` makes it true:

> Valeurs invalides:
>  Argument: log, Donné: true, Choix: null, "info", "debug", "trace"

In the end, there is no way to specify the parameter and to give it a null value.

Maybe adding a "default" value could help having the default behavior.

**Comment by rprieto** [comment]
Thanks, that's a good catch! The help text says

```
--log Print a detailed text log [choices: null, "info", "debug", "trace"] [default: null]
```

But `null` isn't actually a valid option, it's a mistake in the text. Sorry!

The only way to get the nice rendered output is to omit the `--log` parameter. Is that an option for you? Otherwise we could have another special value like `--log default`.

**Comment by rprieto** [comment]
Hi @oupala, this is fixed on `master` and will be in the next version.

**Comment by oupala** [comment]
Fix confirmed. Thanks!
