### ISSUE TITLE
no error when theme is not found

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#155]
When I specify a theme with the `-theme-path "./path/to/theme-classic-modified"` parameter, there is no error when the theme path is not found.

All images are correctly generated, but there is no html, nor css nor js.

An error message should be outputted saying that the theme path is incorrect.

**Comment by rprieto** [comment]
Hi, this is odd. When I try locally I get 

```
> thumbsup --input images --output tmp --theme-path ./foobar

✔ Indexing folder
✔ Resizing media
 ⠙ Creating website

Unexpected error Error: Invalid theme structure in /projects/thumbups/foobar
```

In your case was the path valid? Were there missing files inside the theme folder?

**Comment by oupala** [comment]
You're right. I don't remember exactly how to generate the error.

If I succeed in reproducing the issue, I'll reopen it.
