### ISSUE TITLE
example on how to use a json config file

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#157]
## Feature request

Documentation should include an example about how to use a json config file. For people that are not used to json, a full example (with multiple parameters) would be great.

And a link to some json documentation would be great also (no possibility to insert comments, how to escape double quotes if one want to insert html in the footer).

**Comment by rprieto** [comment]
Hi, it's a little buried but the documentation is over here: https://thumbsup.github.io/docs/3-configuration/misc-settings/. I just added some more detail around the areas you mentioned.
