### ISSUE TITLE
how to use cleanup in a json config file

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#158]
Question: how should we use the `cleanup` parameter when using a json config file.

As cleanup does not take a value, it is not fitting into the json config file.

An example would be more than welcome.

**Comment by oupala** [comment]
An example is given is the associated issue #33, should be in the documentation as the usage in the CLI and in the json config file differ.

**Comment by rprieto** [comment]
Thanks! I added an example in https://thumbsup.github.io/docs/3-configuration/misc-settings/.
