### ISSUE TITLE
Fullscreen mode? 

### ISSUE THREAD

**Issue by vincent090** [thumbsup/thumbsup#160]
First of all - Love this, thx for your time!

## Feature request

Is it possible to set which controllers should be visible? I would like to be able to view the images in fullscreen mode (zoom) but its not enabled by default. Im guessing its a css things, but would be neat to be able to express which lightbox controllers one could activate?

**Comment by vincent090** [comment]
F11 is good enough (fullscreen) - but was thinking more on how to setup/change something with lightbox from thumbsup.

**Comment by rprieto** [comment]
Hi, by full screen do you mean hiding all buttons (info, download...) and the previews at the bottom? I think this might be LightGallery configuration indeed.

For now there's no built-in way to customise the options, but a quick workaround is to fork a theme and change the hard coded options.

**Comment by rprieto** [comment]
Related issue: #137

**Comment by rprieto** [comment]
Hi @vincent090, sorry I'm only coming back to this issue now!

I noticed that LightGallery has a built-in fullscreen control, and I just made it one of the default controls. It will be in the next release. You can also start using it today by cloning https://github.com/thumbsup/theme-classic and specifying `--theme-path ./git/theme-classic` (or any other themes).

If you want more control over other lightgallery options, you can also
- fork a theme and change the options
- suggest that some of these options become theme settings, which can now be controlled via `--theme-settings`
