### ISSUE TITLE
album url slug for name containing '

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#164]
It appears that url slug does not escape `'` character when generating album url.

You can maybe use the standard [slugify](https://www.npmjs.com/package/slugify) npm package to do so, using a configuration mentionned in the documentation of slugify:

> For example, to remove *+~.()'"!:@ from the result slug, you can use slugify('..', {remove: /[*+~.()'"!:@]/g}).

This would make thumbsup more reliable.

**Comment by oupala** [comment]
I just saw that directory in `media` directory (which are named by the album name) are not escaped either.

**Comment by rprieto** [comment]
Hi, which version of thumbsup are you using? The album names / URL should already be slugified.

The media folders though are not slugified, they are named as per the input. That's a good idea, although a big breaking change. I'll have a look to see if we can make it optional.

**Comment by oupala** [comment]
I'm using version 2.10, the last one. Albums slug are mostly slugified, but not completely. For example, simple quotes are not removed.

And for albums folder in the media directory, they are not slugified. I agree it is a big change, and a breaking change, but I think it is mandatory if you want thumbsup to be robust.

**Comment by rprieto** [comment]
Hi @oupala, the album filenames use your suggested slug on master. I will make "slugifying media folders and media filenames" another issue, because it requires more planning.

**Comment by oupala** [comment]
Fix confirmed. Thanks!

Have you created the other issue about *lugifying media folders and media filenames*?

I can't see it in the issues' list.
