### ISSUE TITLE
What metadata is available?

### ISSUE THREAD

**Issue by bdillahu** [thumbsup/thumbsup#167]
## question/feature request

Can anybody give a pointer as to what metadata is available? I've seen reference to stuff like:

file.meta.city

or the like, but it didn't seem to work for me, and I am kind of fishing in the dark.

Kind of related, is there a way to control what metadata the exif "sidebar" shows and doesn't show?

Thanks!

**Comment by rprieto** [comment]
Hi, thanks for the reminder! I just updated the docs at https://thumbsup.github.io/docs/4-themes/data-model/. For now, there is no `city` field, although I have idea on how to fetch it from the lat/long.

The EXIF side panel displays the following fields: https://github.com/thumbsup/thumbsup/blob/master/src/website/theme-base/partials/thumbnail.hbs. They are read and displayed by the https://github.com/amcolash/lg-exif plugin.

**Comment by bdillahu** [comment]
Thanks... I might suggest just tying the city field to the existing IPTC location stuff (country, city, state, sublocation) and use data that is there - I use various other tools to populate it, although if thumbsup wanted to do a lookup if it was blank that would be fine by me.

**Comment by rprieto** [comment]
Thanks, I didn't realise IPTC already had these fields. Do you have an example of a photo where they're set?

**Comment by bdillahu** [comment]
Sure... attaching a file.

![2000-08-26T19 31 37_DSC00021 -- dane](https://user-images.githubusercontent.com/2058566/58752446-d708cc80-847c-11e9-8065-86670fa611a0.JPG)

Using exiftool you'll see:

City                            : Stockbridge
Sub-location                    : 424 Walnut Creek Drive - Dillahunty house
Province-State                  : Georgia
Country-Primary Location Name   : United States of America

**Comment by rprieto** [comment]
Thanks, I'll give it a try! (*I've removed the file for privacy reasons*).

**Comment by rprieto** [comment]
Exiftool parses the fields perfectly :+1: However only actual EXIF fields are passed to the `lg-exif` plugin. I'll see what would need to change to render IPTC/XMP fields too.

**Comment by zibous** [comment]
To get the  IPTC/XMP you need to modify the "/thumbsup/src/model/metadata.js".

```
class Metadata {
    constructor(exiftool, picasa, opts) {
        // standardise metadata
        this.date = getDate(exiftool)
        this.caption = caption(exiftool)
        this.keywords = keywords(exiftool, picasa)
        this.video = video(exiftool)
        this.animated = animated(exiftool)
        this.rating = rating(exiftool)
        this.favourite = favourite(picasa)
        const size = dimensions(exiftool)
        this.width = size.width
        this.height = size.height
        this.exif = opts ? (opts.embedExif ? exiftool.EXIF : undefined) : undefined
        // ----------------------------------------
        this.all = exiftool  // <-- add this to get all
        // ----------------------------------------
            // metadata could also include fields like
            //  - lat = 51.5
            //  - long = 0.12
            //  - country = "England"
            //  - city = "London"
            //  - aperture = 1.8
    }
}
```

```
data-city="{{meta.all.IPTC.City}}"
```
But you have also to modify the EXIF side panel, because this will not render the "data-city" attribute.
