### ISSUE TITLE
New theme with own settings

### ISSUE THREAD

**Issue by zibous** [thumbsup/thumbsup#168]
## Feature request

```
Thumbsup version: 2.10.0
Node version: v11.14.0
NPM version: 6.9.0
Operating system: macOS High Sierra v 10.13.6

Gallery generated successfully!      
164 albums, 23413 photos, 235 videos  
```

I have created a new theme that allows me to use additional settings so that I can use these settings in the templates. Would be nice if these could be adopted. I think it's a good option as a generic approach to processing.

```bash
thumbsup --config config.json

config.json
{
    "input": "PATH TO OUTPUT",
    "output": "./fotobuch",
    "title": "Fotobuch AUTOR",
    "include-raw-photos": false,
    "photo-quality": 90,
    "thumb-size": 360,
    "large-size": 1200,
    "embed-exif": true,
    "sort-albums-by": "title",
    "sort-albums-direction": "desc",
    "theme-path": "PROJECTFOLDER/theme-cards-flow/theme",
    "cleanup": true,
    "footer": "<center><span>All images courtesy of </span><a href=\"...\">WEBSITEURL</a></center>",
    "settings": "PATH TO PROPERTYFILE.json"
}

```
![thumbsUp_app](https://user-images.githubusercontent.com/30198737/58380679-403b9c00-7fb4-11e9-87b3-5ff846007dde.png)

Modifications see: https://bitbucket.org/peter_siebler/theme-cards-flow/src/master/thumbsup/
Theme see: https://bitbucket.org/peter_siebler/theme-cards-flow/src/master/

Many thanks to @rprieto  for the excellent programming, it's really fun to work with this application.

**Comment by rprieto** [comment]
That's a great idea! I like the settings file, it's very flexible. I'll add this shortly so you can use the new version.

Glad you're enjoying thumbsup 🙂

**Comment by zibous** [comment]
@rprieto 

Thanks Romain.

 I'm still trying to find a solution to apply the same method for an album and a media item (photo). 

Any attributes could be used to render the templates.

````
{
    "input": "PAHT",
    "output": "PAHT",
    "title": "TITLE",
    "include-raw-photos": false,
    "photo-quality": 90,
    "thumb-size": 360,
    "large-size": 1200,
    "embed-exif": true,
    "sort-albums-by": "title",
    "sort-albums-direction": "desc",
    "theme-path": "PATH",
    "cleanup": true,
    "gallery_settings": "PATH/developset.json",
    "album_settings": "album.json",
    "photo_settings": "*.json"
    "log": null
}

````
**Lightgallery** and **EXIF Data
I'm trying to modify lg-exif.js, because it gives me too few data, since only EXIF data in the media tag (data- *) can be displayed. 

A representation of the data on the EXIF data of the photo does not work because the generate removes all EXIF data  and therefore can not be read.

The solution over the data attributes enlarges the HTML file, so it would be better to solve this with a separate file, which is loaded only when the data is displayed. 

This would also give better flexibility, since everyone could manage this data themselves or could generate it via the EXIF Toool.

**Comment by rprieto** [comment]
Hi @zibous, I just added theme settings to the `master` branch, do you want to give it a try?

For consistency, I called the option `--theme-settings` (similar to `--theme-path` and `--theme-style`). I updated the data model to be 

```js
{
  settings: settings,
  gallery: gallery,
  breadcrumbs: breadcrumbs,
  album: album
}
```

so you can access the variables in the template using `{{ settings.ATTRIBUTE }}`. If you're inside another object, you must use `@root`:

```hbs
{{#each albums }}
   {{ name }}
   {{ @root.settings.ATTRIBUTE }}
{{/each}}
```

Thanks again for the suggestion!

*ps:* 23,000 photos, that's an impressive gallery ❗I'd love to hear about how you use thumbsup, if the performance is OK, and any other ideas you have.

**Comment by zibous** [comment]
Hi @rprieto 

Thanks, performance is perfect, no problem.

Test for new Lightgallery and **EXIF Data.
I have a new plugin for the Lightgallery that shows **ALL** "data-ATTRIBUTES" or data from a json file.

see: https://bitbucket.org/peter_siebler/theme-cards-flow/src/master/theme/public/lightgallery/js/lg-metadata.js

Modified **thumbsup/model/metadata.js** to get all data.
```
class Metadata {
    constructor(exiftool, picasa, opts) {
        // standardise metadata
        this.date = getDate(exiftool)
        this.caption = caption(exiftool)
        this.keywords = keywords(exiftool, picasa)
        this.video = video(exiftool)
        this.animated = animated(exiftool)
        this.rating = rating(exiftool)
        this.favourite = favourite(picasa)
        const size = dimensions(exiftool)
        this.width = size.width
        this.height = size.height
        this.exif = opts ? (opts.embedExif ? exiftool.EXIF : undefined) : undefined
        this.all = exiftool. // <---- NEW
            // metadata could also include fields like
            //  - lat = 51.5
            //  - long = 0.12
            //  - country = "England"
            //  - city = "London"
            //  - aperture = 1.8
    }
}
```

```
// add this to the main template
<link rel="stylesheet prefetch"  href="{{relative 'public/lightgallery/css/lg-exif.min.css'}}" /> 
<script src="{{relative 'public/lightgallery/js/lg-metadata.js'}}"></script>
 
// this is the modification for the new layer.
 <script type="text/javascript">
       $("#media").lightGallery({
             controls: true,
             loop : true,
             download: false,
             counter: false,
             videojs: true,
             videoMaxWidth: "2000px",
             metatitle: "Foto Metadata",   			// layer title
             metakeys: { 'filename': 'Dateiname', 	// translation
                         'datetimeoriginal':'Aufnahme Datum', 
                         'model':'Kamera Modell', 
                         'city':'Stadt', 
                         'sub-html':'Beschreibung', 
                         'make':'Marke' },
             exThumbImage: 'data-exthumbimage'
         });
</script>
```

For json file:
```
<div id="media-id{{this.id}}"  data-meta="{{relative urls.large}}.json" ....
```
The  json file method is not finish, only draft because I do not know to create the EXIF json with thumbups.
