### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by markwk** [thumbsup/thumbsup#17]
What about adding lazy loading onto the galleries? This would mean only automatically loading the first X thumbnails and loading others as one scrolls down. 

This might be a feature to pass on but since I live in one of the internet dead zones of the world (China), data loads due matter and a bigger gallery of mine ends up at over 1MB with thumbnails, I thought I'd mention it.

**Comment by rprieto** [comment]
I’ll close this issue as there hasn’t been any activity for a while. This is still a very good idea for large galleries. Thumbsup now supports custom themes so it should be easy to add lazy loading, and potentially for the official themes to follow at some point.
