### ISSUE TITLE
Newest push breaks functionality (but thanks for HEIC!)

### ISSUE THREAD

**Issue by scubachristopher** [thumbsup/thumbsup#170]
## Bug report

+ echo 'Making gallery...'
Making gallery...
+ echo

+ cd /root
+ DEBUG='*'
+ thumbsup --input /mnt/external3tb/Netshare/Pictures/ --output /mnt/external3tb/Gallery/ --thumb-size 240 --albums-from date --albums-date-format YYYY/MM --sort-albums-by title --original-photos --original-videos --title 'Christopher Yates Family Photos' --theme cards --cleanup
/usr/lib/node_modules/thumbsup/node_modules/boxen/index.js:26
			...detail
			^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/bin/messages.js:2:15)
+ cd -

So I updated via npm install -g thumbsup, then tried my script.  I received the above error.  I had renamed my 'thumbsup' before upgrading, so switched back and have the same error.  Now running 'thumbsup' with any command line parameters throws the same error.

**Comment by rprieto** [comment]
Hi @scubachristopher, sorry for the broken behaviour. What version of Node.js are you using? Since version `2.10.1` it doesn't support Node 4 anymore, which is out of long term support.

**Comment by scubachristopher** [comment]
[root@syncbox ~]# node -v
v6.16.0

![image](https://user-images.githubusercontent.com/10871350/59512674-7d12f880-8eb9-11e9-8a0a-aad52ef05237.png)

Seems the "...detail" is what it is identified as the issue.  Don't know node so not sure how to solve.  Thank you for being responsive to my issue -- much appreciated.

**Comment by rprieto** [comment]
Interesting. That's the spread operator, which is apparently only supported on objects in Node 8+.

I'll check which dependency introduced that. Is it possible for you to upgrade to Node 8?

**Comment by scubachristopher** [comment]
Good point but no luck:

![image](https://user-images.githubusercontent.com/10871350/59523057-907d8e00-8ed0-11e9-80c1-d8728add1063.png)

**Comment by rprieto** [comment]
I think this error happens when you upgrade node, but don't rebuild a previously-built application that has native modules.

Could you reinstall thumbsup?

**Comment by scubachristopher** [comment]
Am off to Italy for 2 weeks, so I will try this when I return.

**Comment by scubachristopher** [comment]
Chao!

Completely removed anything having to do with node or npm or thumbsup.  Installed node.  Tried to install thumbsup:

[root@syncbox ~]# npm install -g thumbsup
/usr/bin/image-size -> /usr/lib/node_modules/image-size/bin/image-size.js
/usr/bin/mime -> /usr/lib/node_modules/mime/cli.js
/usr/bin/mkdirp -> /usr/lib/node_modules/mkdirp/bin/cmd.js
/usr/bin/errno -> /usr/lib/node_modules/errno/cli.js
/usr/bin/semver -> /usr/lib/node_modules/semver/bin/semver
/usr/bin/sshpk-conv -> /usr/lib/node_modules/sshpk/bin/sshpk-conv
/usr/bin/sshpk-sign -> /usr/lib/node_modules/sshpk/bin/sshpk-sign
/usr/bin/sshpk-verify -> /usr/lib/node_modules/sshpk/bin/sshpk-verify
/usr/bin/uglifyjs -> /usr/lib/node_modules/uglify-js/bin/uglifyjs
/usr/bin/uuid -> /usr/lib/node_modules/uuid/bin/uuid
/usr/bin/which -> /usr/lib/node_modules/which/bin/which
/usr/bin/rimraf -> /usr/lib/node_modules/rimraf/bin.js
/usr/bin/handlebars -> /usr/lib/node_modules/handlebars/bin/handlebars
/usr/bin/JSONStream -> /usr/lib/node_modules/JSONStream/bin.js
/usr/bin/lessc -> /usr/lib/node_modules/less/bin/lessc
/usr/bin/thumbsup -> /usr/lib/node_modules/thumbsup/bin/thumbsup.js

> integer@2.1.0 install /usr/lib/node_modules/integer
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/integer/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/integer/.node-gyp'
gyp ERR! System Linux 3.10.0-957.5.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/integer
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-01T09_36_17_680Z-debug.log
[root@syncbox ~]# node-gyp rebuild
bash: node-gyp: command not found...
[root@syncbox ~]# node -v
v10.16.0


So... not sure what to do next and could use your guidance.

**Comment by rprieto** [comment]
Hi, it looks like a permission issue (access to `/usr/lib/`). You could maybe run as sudo, but I think it's preferable to do something like
- setting the right access instead like https://timonweb.com/posts/install-npm-packages-without-sudo/
- using `npm config set prefix ~/.npm
` like in https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92.

**Comment by scubachristopher** [comment]
Closer.  Was just using root (hides in shame).  Create me as local user, installed thumbsup, granted some perms.  Failing on GM but it's there:

+ cd /home/chris
+ DEBUG='*'
+ sudo thumbsup --input /mnt/external3tb/Netshare/Pictures/ --output /mnt/external3tb/Gallery/ --thumb-size 240 --albums-from date --albums-date-format YYYY/MM --sort-albums-by title --original-photos --original-videos --title 'Christopher Yates Family Photos' --theme cards --cleanup

Warning: --original-photos is deprecated
Warning: --original-videos is deprecated
Warning: --albums-date-format is deprecated


Error: the following programs are required to run thumbsup.
Please make sure they are installed and available in the system path.

- gm (http://www.graphicsmagick.org)

+ '[' 1 -ne 0 ']'
+ echo 'Creating gallery failed -- aborting...'
Creating gallery failed -- aborting...
+ exit 1
[chris@syncbox ~]$ gm
GraphicsMagick 1.3.27a 2017-12-11 Q8 http://www.GraphicsMagick.org/
Copyright (C) 2002-2017 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.
Usage: gm command [options ...]

Where commands include:
      batch - issue multiple commands in interactive or batch mode
  benchmark - benchmark one of the other commands
    compare - compare two images
  composite - composite images together
    conjure - execute a Magick Scripting Language (MSL) XML script
    convert - convert an image or sequence of images
       help - obtain usage message for named command
   identify - describe an image or image sequence
    mogrify - transform an image or sequence of images
    montage - create a composite image (in a grid) from separate images
       time - time one of the other commands
    version - obtain release version
[chris@syncbox ~]$ node -v
v10.16.0
[chris@syncbox ~]$


VERY MUCH appreciate your time and support.

**Comment by rprieto** [comment]
Maybe `gm` is in the user's PATH, which is lost with sudo. Do you have to run thumbsup as sudo? Otherwise does `sudo env "PATH=$PATH" thumbsup ...` help?

**Comment by scubachristopher** [comment]
Ok that got me there!  Processing 40k items.  If it fails, I'll call out.

THANK YOU!

**Comment by scubachristopher** [comment]
Ok, 2 issues I see:

1).  Imagemagick doesn't have the HEIC option as a part of the standard build.  I'm on Centos 7 and have built it with the .configure option to enable HEIC, but it's not building with that.  Seems there are dependencies on dev builds of libraries that I've struggled to build locally.  I'll continue to wrestle with this, but any guidance would be great.  Is there a reason you can't build these and include the tools?  Would be great to the non-system admins that are as incompetent as me.

2).  I am seeing these un00fin00.html files as output.  What does that mean?

Thanks!

**Comment by rprieto** [comment]
For 1) I prefer to rely on local installations so that we're not responsible for building/finding the right binaries for every architecture. This is usually not a problem, except for ImageMagick indeed because it has to be built from source for HEIC support.

If you can, you could run the Docker image instead, which bundles every dependency thumbsup can need (Gif support, RAW support, HEIC...).

For 2) no idea yet, is looks like `undefined.html` with some zeros. Very strange, let me know if you find more info.

**Comment by rprieto** [comment]
In fact `un00fin00` looks like date formatting gone wrong. There might be a bug in `-albums-date-format`.

This option is deprecated, can you try `--albums-from "{YYYY/MM}"` instead?

**Comment by scubachristopher** [comment]
Update:
- Still stuck compiling with the correct voodoo to get HEIC with Imagemagick.
- The --albums-from "{YYYY/MM}" works and solves the un00fin00 stuff.

In the mean time, I decided to try docker.  Am Centos 7, fresh docker install.  Here's what I get:

___________________________________________________

[root@syncbox chris]# docker run -t                -v `pwd`:/work             -u $(id -u):$(id -g)       thumbsupgallery/thumbsup   thumbsup --input /mnt/external3tb/Netshare/Pictures/ --output /mnt/external3tb/Gallery/ --thumb-size 240 --sort-albums-by "title"  --title "Chris Photos" --theme "cards" --cleanup --albums-from "{YYYY/MM}"

internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error relocating /thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/thumbsup/node_modules/better-sqlite3/lib/database.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[root@syncbox chris]# docker -v
Docker version 18.09.7, build 2d0083d
[root@syncbox chris]# docker image ls
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
thumbsupgallery/thumbsup   latest              6dc3fad88d14        2 weeks ago         301MB
hello-world                latest              fce289e99eb9        6 months ago        1.84kB
[root@syncbox chris]# uname -a
Linux syncbox 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@syncbox chris]#

___________________________________________________

Finally, in my bash script that launches the installed version, I fire thumbsup this way:

DEBUG="*"  thumbsup --input /mnt/external3tb/Netshare/Pictures/ --output /mnt/external3tb/Gallery/ --thumb-size 240 --sort-albums-by "title"  --title "Chris Family Photos" --theme "cards" --cleanup --albums-from "{YYYY/MM}"

Couldn't figure out how to launch with docker with DEBUG="*".  Can you help me understand why the docker image doesn't work, and how I can add debug to launching with docker?  Would prefer the docker solution if we can make it work, as it should given it's a container.

Thanks!

**Comment by rprieto** [comment]
There's an issue with the latest Docker version, sorry (#175). The image `thumbsupgallery/thumbsup:2.10.1` should work well.

**Comment by scubachristopher** [comment]
Update:

-  Was able to run 2.10.1.
-  Though I ran "sudo usermod -aG docker chris", I am unable to run docker as non-root.  But ok, here's what I am seeing.  I have a disk mounted with source pics (/mnt/external3tb/Netshare/Pictures/...).  Touched it, then ran the docker image:

__________________________________________________________________


[root@syncbox ~]# touch /mnt/external3tb/Netshare/Pictures/2019/06\ June/IMG_7978.jpg
[root@syncbox ~]# docker run -ti -v `pwd`:/work -u $(id -u):$(id -g) thumbsupgallery/thumbsup:2.10.1  thumbsup --input /mnt/external3tb/Netshare/Pictures/ --output /mnt/external3tb/Gallery/ --thumb-size 240 --albums-from "date" --sort-albums-by "title"  --title "Chris Family Photos" --theme "cards" --cleanup --albums-from "{YYYY/MM}"

┌────────────────────────────────────────────────────────────────────────────────┐
│                                                                                │
│  Thanks for using thumbsup!                                                    │
│                                                                                │
│  Don't forget to check out the docs at https://thumbsup.github.io/docs.        │
│                                                                                │
│  When building a gallery, thumbsup reports anonymous stats such as the OS and  │
│  gallery size. This is used to understand usage patterns & guide development   │
│  effort. You can disable usage reporting by specifying --no-usage-stats.       │
│                                                                                │
│  This welcome message will not be shown again for this gallery.                │
│  Enjoy!                                                                        │
│                                                                                │
└────────────────────────────────────────────────────────────────────────────────┘

  ✔ Indexing folder
  ✔ Resizing media
  ✔ Cleaning up
  ✔ Creating website

┌───────────────────────────────────┐
│                                   │
│  Gallery generated successfully!  │
│  1 albums, 0 photos, 0 videos     │
│                                   │
└───────────────────────────────────┘

__________________________________________________________________

-  So then I switched back to my script that launches the local installed version (w/o HEIC) to demonstrate what I expect:

__________________________________________________________________




[root@syncbox ~]# su chris
[chris@syncbox root]$ cd
[chris@syncbox ~]$ touch /mnt/photo/2019/06\ June/IMG_7978.jpg
[chris@syncbox ~]$ ./make_gallery.sh

Syncing photos


Skipping Cloudformation stuff, but it's in the script...


Making gallery...


  ⠼ Indexing folder
  ✔ Indexing folder
  ✔ Processing media
  ✔ Cleaning up
  ✔ Creating website


 Warning: there was an issue with 284 files.
 Please check the full log for more detail.

┌─────────────────────────────────────────┐
│                                         │
│  Gallery generated successfully!        │
│  252 albums, 38132 photos, 3778 videos  │
│                                         │
└─────────────────────────────────────────┘

/home/chris

Pushing to S3...

__________________________________________________________________

-  Can you please explain how to launch the container with DEBUG="*"?
-  thumbsup.log is not written, so there are no fingerprints associated with the docker run.  How else can I see what's going on when it runs?

Thanks

**Comment by rprieto** [comment]
I should clarify the Docker documentation.

To expose data to a Docker container, you must mount the paths from the host. The example uses an over-simplified `docker run -ti -v $PWD:/work`. In your case you could mount the input and output folders separately:

```bash
docker run [...]
-v /mnt/external3tb/Netshare/Pictures:/input:ro   # read-only input to be safer
-v /mnt/external3tb/Gallery:/output                        # read-write output
thumbsupgallery/thumbsup --input /input --output /output
```

The `thumbsup.log` file should be in the output folder at the end, and will contain details about the 284 files that failed.
To launch with DEBUG in Docker, you must pass the environment variable as `docker run -e "DEBUG=*" [...]`

**Comment by scubachristopher** [comment]
Yeah, stupid of me not to dig into docker run more -- thanks for the help.  Works!

One question though -- each time I recreate the website, I am aws s3 sync'ing to my S3 bucket.  All good.  When I regenerate the site, of course the .html files have to go up as they were just created.  But does everything under public get regenerated?  Seem you might be cp'ing that each time you generate a new site.  Instead, perhaps you can cp -p so the timedate remains as the original in source.  This way it won't have to get resync'd each time though there is no change.

Again, thanks so much for the help!

**Comment by rprieto** [comment]
I didn't know about `cp -p`, it's a good tip thanks! Can you open a new issue to track it more easily please? (I can't look at it right away)
