### ISSUE TITLE
Problems with path settings

### ISSUE THREAD

**Issue by zibous** [thumbsup/thumbsup#171]
If running as an npm package:

```
Thumbsup version: Latest
Node version: v10.15.3
NPM version: 6.4.1
Operating system: macOS High Sierra
```
I keep stumbling over the PATH settings, can do relative and some must be done absolutely.

```
"input" ... worked relative and absolute
"output" ... worked relative and absolute
"theme-path" ... works only absolute
"--theme-settings" ... works only absolute
```

It would be good if all settings were absolute or relative.

--theme-settings, would be good if synonymous here the "--config" settings are available.

**Comment by rprieto** [comment]
Great catch, I'll update the theme path/settings to allows relative paths :+1:

I didn't understand what you suggest with theme-setting and config. Can you elaborate?

**Comment by zibous** [comment]
@rprieto 
Thanks, see:

```
function readThemeSettings(opts) {
    const filepath = opts.themeSettings;
    if (!filepath) {
        return {}
    }
    var content = fs.readFileSync(filepath).toString()
    try {
        var cfg = JSON.parse(content)

        // new add input and output settings
        cfg.inputfolder = opts.input
        cfg.outputfolder = opts.output
        return cfg

    } catch (ex) {
        throw new Error('Failed to parse JSON theme settings file: ' + filepath)
    }
}
```

**Comment by rprieto** [comment]
Hi,

About the paths, do you have an example that fails? The following code works well for me:

```bash
thumbsup --input ../fixtures --output ../tmp --theme-path ../theme-cards --theme-settings ../theme-cards/test.json
```

I like your idea of exposing some of the arguments (or even all of them). One downside is that deprecating arguments will become more work if themes are relying on them. What's an example use case of using them in a theme?

**Comment by zibous** [comment]
Hi @rprieto 

i was struggling to set the real path, because i have the config file in the theme directory. Sorry all is working, it was my mistake..

**Comment by rprieto** [comment]
I think the paths must be relative to the current working directory, not the location of the config file. Happy it's working ok!
