### ISSUE TITLE
Set options.sortAlbumsDirection by Level 

### ISSUE THREAD

**Issue by zibous** [thumbsup/thumbsup#179]
## Feature request
```
Thumbsup version: thumbsup@2.12.0
Node version:  v11.14.0
NPM version:  6.9.0
Operating system: osx
```

Is there a way to define sorting for each level? At the level (deep == 1) I always want to show the newest ones first and vice versa for the albums (deep> 1).

```
Album.prototype.finalize = function(options, parent) {
   ....
  if (this.depth === 1) {
        options.sortAlbumsDirection = "asc"
        this.sort(options)
    } else {
        options.sortAlbumsDirection = "desc"
        this.sort(options)
    }
}
```

A variant of this would be defined in the options:
```
"sort-albums-direction": "desc" // default
"sort-albums-direction": {"1": "asc", "2": "desc", "default": "desc"},
```

Example would be an overview of all trips, here it is better if the last is visible at the top, in the albums of the journey, however, it is more logical if the first trip is displayed first and the last at the bottom.

**Comment by rprieto** [comment]
This sounds like a good idea. With the current arg-parsing module, the simplest way to add this might be

```json
{
  "sort-albums-direction": ["asc", "desc"]
}
```

Any levels past the array would just use the last value. Would that work for you?

**Comment by zibous** [comment]
@rprieto 

Perfect 👍

**Comment by michaelcadilhac** [comment]
That's splendid—that also solve my use case, where I have "months" albums in "years" albums, and find it more natural to have years in reverse, and months in order.  I believe in the long run it would be interesting to have custom mappers being able to specify sort type and order.  Thanks!

**Comment by rprieto** [comment]
Hi @zibous, sorry I'm only getting back to this issue now. The feature is now available on `master` and will go out in the next version. The following flags now support arrays:

```bash
--sort-albums-by
--sort-albums-direction
--sort-media-by
--sort-media-direction
```

If multiple values are provided, they apply to the corresponding nesting-level (first value = root album). They can be specified on the command-line or via config:

```bash
--sort-albums-direction asc,desc
```

```json
{
  "sort-albums-direction": ["asc", "desc"]
}
```

@michaelcadilhac I also really like your idea of sorting at the mapper level. I had a good think about it, there are some options however it's not trivial to implement. I will create another issue for it if there's demand.
