### ISSUE TITLE
Unexpected error ENOENT: no such file or directory, chmod 'site/public/videojs/video.min.js'

### ISSUE THREAD

**Issue by MatthewSteeples** [thumbsup/thumbsup#182]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.12.0
Node version: 8.10
NPM version: 3.5.2
Operating system: Ubuntu Bionic running under WSL on Windows 1903 (yeah... this could be fun!)
```

When generating a site with no videos (just jpg images) I get the following output

>
> ✔ Indexing folder
> ✔ Resizing media
> ✖ Creating website
>   → ENOENT: no such file or directory, chmod '/mnt/c/Users/MatthewSteeples/Downloads/Site2/public/videojs/video.min.js'

> Unexpected error ENOENT: no such file or directory, chmod '/mnt/c/Users/MatthewSteeples/Downloads/Site2/public/videojs/video.min.js'

It spent a few minutes resizing all of the images, so that part seems to work fine, it's just having some issues generating the site.

Looking in the output folder, there is a media folder (with the resized images) and a public folder with a core.css file and an empty videojs folder.

After getting the error I tried installing videojs via npm but that didn't seem to fix it.

Happy to provide any files that will help diagnose it

**Comment by MatthewSteeples** [comment]
I created the missing file in the folder and re-ran the command, but the file was then removed. I also get this warning for videojs

> npm WARN grunt-contrib-uglify@0.2.7 requires a peer of grunt@~0.4.0 but none was installed

Running `grunt --version` gives me

> grunt-cli v1.2.0

**Comment by rprieto** [comment]
Hi, thanks for the detailed report. What theme are you using?

**Comment by MatthewSteeples** [comment]
I hadn't specified a theme so I'm assuming it's defaulted to `classic`. I've just tried running specifying `cards`, `mosaic` and `flow` (as they're listed in the settings) but they all result in the same output

**Comment by MatthewSteeples** [comment]
Doing a `locate` for video.min.js shows that it's in the filesystem in the following location (among others for the other themes)

> /usr/local/lib/node_modules/thumbsup/node_modules/@thumbsup/theme-classic/theme/public/videojs/video.min.js

**Comment by MatthewSteeples** [comment]
I'll stop adding more info now unless there's anything useful you can ask for (as I'm sure this must be annoying) but this is the output from running it with logging set to `Trace`

https://1drv.ms/t/s!At3esDCvFltcgaDbGgaaabGN09zPuGY?e=alRgVV

**Comment by MatthewSteeples** [comment]
Really last update now I promise, but I was able to get it running in the provided Docker container, so it must just be something to do with WSL. I'm happy to help diagnose it if you're interested in resolving it, otherwise you can close this issue

**Comment by rprieto** [comment]
Sorry I missed your updated. Unfortunately I don't have a similar environment to help troubleshoot. I'm glad you had it working with Docker.

I'll close the issue, but we can reopen it if someone else is facing issues with WSL.
