### ISSUE TITLE
Use my own thumbnail

### ISSUE THREAD

**Issue by rokenbuzz** [thumbsup/thumbsup#183]
## Feature request
My own app is generating mp4 videos and my own thumbnails for them.
My videos are based on motion detection of surveillance cameras and the thumbs are a zoomed in image of what changed, so this makes sense to be custom. 
Is there a way to make thumbsup use my own thumbnail?
If it's not already a feature I'm not seeing, I can easily do something like make the file name based on the video name but with a .thumbnail extension, like video1.mp4 and video1.thumbnail or some convention, I don't care what. Then thumbsup can only generate a thumb if that file isn't found.
I've tried looking at the code to make this change myself because it seems like it would be dead simple, but so far I'm not seeing where or what to change.
Thanks for considering making this change, or pointing me in the right direction!
rokenbuzz

**Comment by rokenbuzz** [comment]
I found a way to get what I want by modifying steps/actions.js
Added createvideothumbnail to look for a user thumbnail to use.

```
createvideothumbnail = function (task, thumbnail, done)
  {
    userthumb = task.src + '.thumbnail'

    if (fs.existsSync(userthumb)) {
      // user thumbnail file exists, so use it
      fs.copy(userthumb, task.dest, done)
    }
    else {
     // no user thumnnail, so create our own
      downsize.still(task.src, task.dest, thumbnail, done)
    }
  }

  return {
    'fs:copy': (task, done) => fs.copy(task.src, task.dest, done),
    'fs:symlink': (task, done) => fs.symlink(task.src, task.dest, done),
    'photo:thumbnail': (task, done) => downsize.image(task.src, task.dest, thumbnail, done),
    'photo:small': (task, done) => downsize.image(task.src, task.dest, small, done),
    'photo:large': (task, done) => downsize.image(task.src, task.dest, large, done),
    'video:thumbnail': (task, done) => createvideothumbnail(task, thumbnail, done),
    'video:small': (task, done) => downsize.still(task.src, task.dest, small, done),
    'video:poster': (task, done) => downsize.still(task.src, task.dest, large, done),
    'video:resized': (task, done) => downsize.video(task.src, task.dest, videoOpts, done)
  }
```

**Comment by rprieto** [comment]
Hi, that's an interesting use case. The thumbnails in the output folder are only generated
- if the thumbnail file doesn't exist yet
- or if the source file (input) is newer than the thumbnail (output)

Could you generate or copy your custom thumbnails in the *output* folder directly, with the same name thumbsup itself would use?

**Comment by rprieto** [comment]
Hi @rokenbuzz, did you try generating the thumbnails in the output folder, and did it solve the issue?

**Comment by rokenbuzz** [comment]
At some point for some reason I decided to use Unite Gallery instead.

**Comment by rprieto** [comment]
No problem, thanks for letting me know.
