### ISSUE TITLE
Generation skips images with non-ASCII filenames

### ISSUE THREAD

**Issue by skygate2012** [thumbsup/thumbsup#184]
# Bug report

```
Thumbsup version: 2.12.0
Node version: v10.16.0
NPM version: 6.11.3
Operating system: Windows 10 LTSC
```

About the bug...

- Are you getting an error message?
No error message, images with non-ASCII filenames will just be ignored when building.
- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?
Tried but gained no meaningful info.
- Is the behavior different from expected?
Yes.
- Can you provide steps to reproduce the issue?
Name an image file with any non-ASCII characters such as `à.jpg` and run thumbsup.

**Comment by rprieto** [comment]
Hi @skygate2012, sorry for the delay. I can't reproduce this on Linux. Could you please run Thumbsup on a new folder with a single non-ASCII photo, with`--log trace`, and paste the full log below?

**Comment by rprieto** [comment]
Hi, I now have access to Windows and I can reproduce the issue. The file `à.jpg` is actually not indexed and is not listed in the database. The integration tests also run on Windows now so it should be easier to fix.
