### ISSUE TITLE
How to tweak link to original photos

### ISSUE THREAD

**Issue by grayaii** [thumbsup/thumbsup#185]
I am on a Mac.

I'm having trouble getting the photo-preview/photo-download URL to point to the original files.

The original files are here:
/Volumes/share/alex/backedUp/Pictures/Pictures/2019/

When I run the following docker command to generate the website, I can see in my browser that the original files are pointing to here:
file:///Users/alexgray/workspace/allrepos/thumbsup/website/media/original/2019-01-15/pic01.JPG

But SHOULD be here:
file:///Volumes/share/alex/backedUp/Pictures/Pictures/2019/2019-01-15/pic01.JPG

```
docker run -t                   \
  -v /Volumes/share/alex/backedUp/Pictures/Pictures/2019/:/input:ro  \
  -v `pwd`/website:/output      \
  -u $(id -u):$(id -g)          \
  thumbsupgallery/thumbsup      \
  thumbsup --input /input --output /output --include-videos false --photo-preview symlink --photo-download symlink
```

Any ideas how to tweak the link to the originals?
I see there is a "download-link-prefix" option, but it's deprecated.

Thanks a million for this tool!

**Comment by grayaii** [comment]
ok. I think I know what the issue is.
1) I'm using docker to generate the website. 
2) --link-prefix "/Volumes/share/blah/"
The generated file is ALWAY relative when using --link-prefix. Example, the link the orignal photo is:
file:///Users/alex/workspace/allrepos/thumbsup/website/Volumes/share/blah/xgYMVUYbRRKKm4vUeyRQKg_thumb_1239.jpg
But it should be:
file:///Volumes/share/blah/xgYMVUYbRRKKm4vUeyRQKg_thumb_1239.jpg

If I manually tweak index.html to replace Volumes/ with /Volumes/, it works.

My use case is this:
I'm using docker to generate the site locally. The original files are in /Volumes/share/blah/

The only way I can make it work is to manually modify index.html to change the relative paths to be absolute.

**Comment by rprieto** [comment]
Hi, thanks for finding this! You're right, by default it tries to point to the input path _relative to the output path_, which probably doesn't work well in Docker. I should document that.

The `--link-prefix` is indeed the way to go...
and it's probably a bug if it renders `Volumes` instead of `/Volumes`. I'll do some testing on my end. Can you also try `--link-prefix file:///Volumes/share/...`?

**Comment by grayaii** [comment]
I'll give it a shot tonight!
I'm currently running a scan of 200K pictures via docker, so when it's done (hopefully tonight), i'll give it a shot!

**Comment by rprieto** [comment]
Hi @grayaii, did `--link-prefix` solve your issue in the end? Also how did the 200k-picture run go?

**Comment by yacoob** [comment]
I'm in a similar situation: running via docker with `/input` and `/output` as two separate docker volumes. Can't get `--link-prefix` to work sanely. Just for a test, I've used a single docker volume with `--output` and `--input` pointing to two different directories - no avail. Worst thing, however, is the fact that with `--link-prefix 'https://my.tld/proper/path/to/output/hierarchy' I get my browser trying to get the photo from a weird path that looks like `link-prefix` turned into a relative link: `https://my.tld/my.tld/proper/path/to/output/hierarchy/album/image.jpg`

I think it's buggy now. What kind of logs do you need from me to fix this? :D

**Comment by rprieto** [comment]
Hi @yacoob. This is strange. Can you please make a small example with a single photo, and attach the logs generated by `thumbsup <args> --log info`?

How it should work: when using `--photo-preview link` it simply concatenates the link prefix and the original image path, relative to the input folder. For example:

* Input folder = /mnt/photos
* Photo = /mnt/photos/holidays/IMG_001.jpg
* Link prefix = https://example.com/static 
* Resulting URL = https://example.com/static/holidays/IMG_001.jpg 

This is mostly meant for cases where all the input photos are already uploaded somewhere (outside of thumbsup) and you want to avoid re-uploading again and wasting space.

For example:

```bash
thumbsup --input /mnt/photos --output website --photo-preview link \
--photo-download link --link-prefix https://example.com/static/
```

But you can also specify a path on disk:

```bash
thumbsup --input /mnt/photos --output website --photo-preview link \
--photo-download link --link-prefix file:///mnt/photos/
```

This might actually be the best solution for Docker, where the container has no idea what the *actual* hosts paths are, and cannot generate any meaningful link. The other solution would be to mount the folders in the exact same structure as on the hosts, e.g.

```bash
docker run -v /mnt/photos:/mnt/photos -v /home/myuser/website:/home/myuser/website …
```

**Comment by rprieto** [comment]
Hi, the following values are now handled correctly:

- `--link-prefix /photos` => `file:///photos/image.jpg`
- `--link-prefix file:///photos` => `file:///photos/image.jpg`
- `--link-prefix http://example.com` => `http://example.com/image.jpg`
