### ISSUE TITLE
Out of memory on raspberry pi 3 with ~33000 photos/videos to index

### ISSUE THREAD

**Issue by sutolaci** [thumbsup/thumbsup#188]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.12.0
Node version: v8.11.1
NPM version: 6.13.6
Operating system: Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```

Actually the raspbian operating system killed the gm process and  I think then the whole process tree cause of out of memory issue. I have ~33000 photos/videos in the input directory. Could I somehow limit the parallel process numbers or somehow limit the memory usage of the whole application?

- Are you getting an error message? No, the OS killedd the process tree
- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info? No.
- Is the behavior different from expected? Yes, I want to use your application on raspberry pi 3 limited hardware.
- Can you provide steps to reproduce the issue? 
Executed command line:
./node_modules/.bin/thumbsup --config thumbsup.json

thumbsup.json:
{
  "input": "/mnt/gallery",
  "output": "/mnt/tmp/thumbs_gallery/",
  "title": "Fotóalbum",
  "thumb-size": 200,
  "large-size": 1500,
  "download-photos": "symlink",
  "download-videos": "symlink",
  "theme": "flow"
}

Raspberry HW details:
Memory: 1GB
Swap: 100MB

Procinfo:
pi@raspberrypi:~ $ cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 00000000e7309777

**Comment by sutolaci** [comment]
Log attached from dmesg
[dmesg.log](https://github.com/thumbsup/thumbsup/files/4071342/dmesg.log)

**Comment by rprieto** [comment]
Hi, by default thumbsup will run one process per CPU core (4 in your case). Can you try `--concurrency 1` (or 2) to see if it fixes the issue?

**Comment by sutolaci** [comment]
Thank you very much, this solved the problem with a little more added swap. Actualy my raspberry pi throttle itself cause of under voltage so I have to replace my power supply.

Best regards,
Laci

**Comment by rprieto** [comment]
No problem, I'm glad it's working!
