### ISSUE TITLE
update dependency to better-sqlite (v6.0.1)

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#189]
## Feature request

As [integer v3 is now available as a binary](/JoshuaWise/integer/issues/8), updating depedency to integer v3 makes node-gyp and on-the-fly-compilation useless

This would make thumbup really easy to install.

**Comment by oupala** [comment]
I've just seen that integer is not a direct dependency of thumbsup.

```
my-gallery@1.0.0
 └─┬ thumbsup@2.12.0
      ├─┬ better-sqlite3@5.4.3
      │   ├── integer@2.1.0
```

So, first better-sqlite should update its dependency to integer, and this has been done in better-sqlite 6.0.1.

Now thumbsup should update its dependency to better-sqlite 6.0.1.

I update the title of this issue to reflect that the dependency to update is better-sqlite, and not integer.

**Comment by rprieto** [comment]
Thanks @oupala. Thumbsup `2.13.0` is out with the latest version of `better-sqlite`.

**Comment by oupala** [comment]
Change validated.

This is a great progress tin ease the installation of thumbsup.
