### ISSUE TITLE
Boolean inputs are case sensitive?

### ISSUE THREAD

**Issue by kellytrinh** [thumbsup/thumbsup#190]
## Bug report

Operating system:  Windows

When running from command line in Windows to docker instance for "--include-videos" if I pass it "FALSE" it still processes videos (is the boolean case sensitive?)

Best solution would be to make this case-insensitive, failing that - this should be documented in the option man pages.

**Comment by rprieto** [comment]
Hi @kellytrinh, thanks for the report. You are right, boolean flags are case sensitive. This is how the flag-parsing library behaves out of the box. I have updated the documentation accordingly at https://thumbsup.github.io/docs/3-configuration/usage/.
