### ISSUE TITLE
is there a changelog available somewhere?

### ISSUE THREAD

**Issue by oupala** [thumbsup/thumbsup#196]
As thumbsup 2.13.0 has just been made available, I was looking for a changelog, but I couldn't find one anywhere.

Is there a changelog available somewhere?

**Comment by rprieto** [comment]
That's a great point. Today there is no changelog available. I see two options:
- generate a change log automatically. That's ideal but requires to be very strict in commit messages. I had started following the `feature/fix/doc/chore` standard but don't always follow it. It would also require squashing every PR to conform too.
- generate a change log manually

I'll have a think about what can be put in place. I agree it would be very valuable.

**Comment by oupala** [comment]
You should really try to generate the changelog automatically: it is more reliable and simpler.

I agree it obliges you and all contributors to follow strict guidelines about commit message, but these guidelines a way for anyone to improve its way of commiting: if it is hard to find a good commit message, then your commit is probably too big or too small (usually too big).

There is some tools to help you managing these things:

- [semantic-release](https://github.com/semantic-release/semantic-release/) is the reference
- [commitizen](https://github.com/commitizen/cz-cli) and [commit-lint](https://github.com/conventional-changelog/commitlint) are good helpers to enforce these rules

**Comment by rprieto** [comment]
Hi @oupala. Starting with the next version, the [Github releases](https://github.com/thumbsup/thumbsup/releases) will mention the list of commits since the previous version.

**Comment by oupala** [comment]
It is a good thing to have a changelog.

But I would prefer to see it included in the CHANGELOG.md file rather than having to browse to GitHub in order to see what has changed.

**Comment by rprieto** [comment]
Hi @oupala, noted. I might include this in a future version.
