### ISSUE TITLE
Is it possible to capture the thumb image from a video at a certain time?

### ISSUE THREAD

**Issue by thxred** [thumbsup/thumbsup#198]
Most of my videos start in black from the first frames (fadein). I believe, when thumbsup is generating the images from the videos, he grabs the first frames, living my thumb image from the video in black.

**Comment by rprieto** [comment]
Hi, that's a good idea. For now, Thumbsup reads the still at `t=1s` falling back to `t=0s` if that failed.

Would it make sense to have the first value configurable, like `--video-still-seek 5s`? Another option is to read the video length, and always take a still at `t=length/2`.

**Comment by thxred** [comment]
It makes perfect sense. Meanwhile which file should I change to get a difrente value?

**Comment by rprieto** [comment]
If you're running from source, you can modify `node_modules/thumbsup-downsize/lib/index.js` line 73, e.g. `['-ss', '5']` for 5 seconds in.

**Comment by thxred** [comment]
Tanks, that did it!

**Comment by rprieto** [comment]
Hi, the latest version on master has the following CLI arguments:
- `--video-stills <mode>`, which can be `seek` or `middle`
- `--video-stills-seek <seconds>`, which determines how far to seek in in seek mode

In either case, if it fails it falls back to the first frame of the video.
The default is `seek` and `1`.
