### ISSUE TITLE
Cannot get a picasa.ini file to be used

### ISSUE THREAD

**Issue by alexhunsley** [thumbsup/thumbsup#204]
I'm trying to get thumbsup to read a Picasa.ini file but it doesn't seem to make any difference.
 
I have a very simple test setup - a single folder with a single JPG in it, and a file named `Picasa.ini` in that folder, containing:

```
[Picasa]
name=Album description here
[DSCF1940.JPG]
star=yes
caption=Nice sunset
keywords=beach,sunset,alex
```

The photo file is named DSCF1940.JPG so the name matches. But after I generate the gallery I can't see any album name, or a caption on the actual photo. Where should these show up in the interface?

I've tried renaming the `Picasa.ini` file as `picasa.ini` (lower case) and `.picasa.ini` (dot at front), but none of that made any difference.

I've tried grepping all of the output files for `sunset` and there's no mention, so I don't think the metadata is hiding in there somewhere unseen.

I'm running thumbsup 2.14.0 on Mac OS 10.15.5, latest versions of node, npm etc.

**Comment by rosstom2232** [comment]
I'm having the same problem so any solution to this would be much appreciated!

**Comment by rprieto** [comment]
Hi @alexhunsley and @rosstom2232. Sorry for the very slow fix. It was indeed broken and will be back to normal in the next release.

**Comment by itzo** [comment]
@rprieto FYI the docker image is still pointing to 2.15 (which is missing the fix).

**Comment by DarrellMozingo** [comment]
@itzo - looks like the image is now being pushed to [GitHub's container registry](https://github.com/thumbsup/thumbsup/pkgs/container/thumbsup) instead of DockerHub - 2.16 is there with the picasa fix.
