### ISSUE TITLE
Feature request: split albums into multiple pages to limit the number of items displayed at once

### ISSUE THREAD

**Issue by glubsy** [thumbsup/thumbsup#209]
## Problem
I have very large collection of files and displaying them all at once in a album is a problem both for the server and the client.
* server: gets hammered with thousands of GET requests for each thumbnail
* client: the generated HTML page for each album is huge, and it requires a lot of memory and CPU to display very large pages in browser, sometimes making the browser very laggy.

## Solution
* Add an option to limit the total number of items displayed per generated html page, 
ie. ``--maximum-items [number] [default: 50]``
* For each page generated, links to other pages from the same album should be placed in the footer of each page.

Maybe going with a structure like this:
```
output                          output
  |__ index.html                  |__ index.html
  |__ albums                      |__ albums
  |   |__ holidays.html           |   |__ holidays.html
  |   |__ birthdays.html  --->    |   |__ holidays-2.html
  ...                             |   |__ holidays-3.html
                                  |   |__ birthdays.html 
```
Would it be hard to implement? What should one look for as a starting point? Is this mostly implementable through the themes?

**Comment by nikhilweee** [comment]
+1. Definitely feel the need for pagination.

**Comment by rprieto** [comment]
Hi, this is a very good idea. It's not something themes can do directly: they only render HTML content for each album, they don't have control over the files being written.

I started looking into adding this to the core. It's not trivial but I will report progress. So far I'm leaning towards the renderer being called N times per album, each time with a subset of files. It has to be in a way which is transparent, i.e. the theme not having to be aware is rendering a full album or a "page". The only hint will be a list of pages and HTML links to be rendered at the bottom.

**Comment by rprieto** [comment]
I’m also investigating the alternative, with a new `album.page` object in addition to `album.files`.
The main advantage is that themes that aren’t page-aware will still work properly, simply displaying all files as usual.
Newer themes could support the following:

```hbs
<!-- Render links to all pages -->
<nav class="pages">
  {{#each pages}}
    <a class="page" href="{{relative url}}">{{index}}</a>
  {{/each}}
</nav>

<!-- Render the active page (note "page" instead of "files") -->
<ul id="media">
  {{#each page}}
    {{> thumbnail}}
  {{/each}}
 </ul>
```

**Comment by rprieto** [comment]
Hi @glubsy and @nikhilweee, this will be available in the next published version.
You can specify the page size using `--album-page-size`. The default is to include all files.

I will update the core themes to render the page links when there is more than 1 page. It looks like this:

![image](https://user-images.githubusercontent.com/189105/97928135-a9593e80-1d66-11eb-9f04-5d19a9f5aa93.png)

**Comment by glubsy** [comment]
Woohoo thank you very much @rprieto ! This looks just great. I'll test this and report back if there is any issue. Much appreciated!

**Comment by glubsy** [comment]
It works just fine so far. Packages on NPM might need to be updated someday though. ;)

**Comment by rprieto** [comment]
Thanks for the update @glubsy! I will publish a new version soon, including support in the main themes.
