### ISSUE TITLE
Thumbnail name should include the full corresponding filename+extension

### ISSUE THREAD

**Issue by glubsy** [thumbsup/thumbsup#214]
## Problem
Files often have similar names, but different extensions.
Let's assume I have 4 files:
```
file01
file01.jpg
file01.mp4
file01.webm
```
All these files will get the same thumbnail, regardless of their actual content. But it turns out that they are all completely different files and should not share the same thumbnail.

## Solution 
Generate thumbnails with the full filename+extension. Currently, only the filename (without extension) is used to generate the thumbnail. For the example above we would have:
```
file01.jpg
file01.jpg.jpg
file01.mp4.jpg
file01.webm.jpg
```

**Comment by rprieto** [comment]
Hi, I believe this is already fixed when using`--output-structure suffix`. You can see the code at https://github.com/thumbsup/thumbsup/blob/master/src/model/structure.js.

I'd rather not touch the older Folder mode as it would require re-building galleries, and some people (including myself) run Thumbsup on 100GB+ galleries.

**Comment by glubsy** [comment]
That's right! My bad! Totally overlooked it. It seems to be the most sensible approach, maybe it should be the default mode to avoid this type of problem?

**Comment by rprieto** [comment]
I agree it should be the default! I don't want to change the default behaviour unexpectedly (big rebuilds), but I'll add it to the list for major V3 changes.
