### ISSUE TITLE
Donation Button

### ISSUE THREAD

**Issue by dolie** [thumbsup/thumbsup#215]
## Feature request

Hello,
Thank you for this incredible work.  
Everything is easy and customizable.  
I had some difficulties to use it on Debian server (installation failure with better-sqlite3...) so I used Docker (only worked with `su -` privileges).  

Where is the donation Button ?

Best regards

**Comment by rprieto** [comment]
Hi @dolie, I'm glad you're enjoying thumbsup! Thanks for sharing your experience. I see better-sqlite3 seems to have issues on some systems. It's good that you got it working in Docker.

Do you mean donation button like donating to the project itself? There's nothing like that but thanks for asking! If you enjoy thumbsup you can simply spread the word about the project, and of course any code contribution is also very welcome.
