### ISSUE TITLE
Random 2x2 preview

### ISSUE THREAD

**Issue by nthnca** [thumbsup/thumbsup#223]
## Feature request

I am using the classic theme. In the index pages there are 2x2 previews of each folder. Perfect.

Can these 2x2 previews be randomly selected, instead of just the first 4 pictures in the album? Or if not randomly selected the 1st, 1/4+1, 2/4+1, and 3/4+1 pictures? (if that makes sense).

Often I find that the 2x2 preview has very similar photos and so doesn't give much of a preview. Choosing photos from throughout the album would make it more representative.

AND

Thanks for the awesome thumbsup tool. Loving it.

**Comment by rprieto** [comment]
Hi, I'm glad you're enjoying thumbsup!

I like the idea of a random selection for the preview. It would make sense behind a flag like `--random-previews`. Do you think it's OK if they are randomly picked every time thumbsup is run, or is it important to keep them "stable" by choosing a given pattern like the one you gave?

**Comment by nthnca** [comment]
I like both ideas.

non-stable is nice because it means users automatically get those little
"Aha" moments of seeing a picture they haven't seen in a while.

stable is nice because it means the index stays familiar to users. You
start to associate pictures to an album instead of constantly seeing new
pictures to represent an album that give you a minute of pause before you
click.

I think if I only get one I would choose stable.

If this is going to be a configuration option I would take both.  :-)

**Comment by rprieto** [comment]
That makes sense, I'm happy to go with something like `--album-previews [first | random | spread]`.

The only thing with `spread` is that the selection will change every time pictures are added to the album, but I don't think there's any way around that.

**Comment by nthnca** [comment]
Perfect.

Thanks again for this amazing tool!

----

Want to be more productive, healthier, and happier? Kelli and I have
started to write about what we have learned over the years. Subscribe to
our newsletter at https://kn8ideas.com/newsletter

**Comment by rprieto** [comment]
Hi @nthnca, this will be released in the next version of Thumbsup.

The only thing you might notice with `spread` is that it's based on the current default of 10 previews. Since most themes only show 4 you'll only see photos from the first half of the album. In the future there could be a way to only force 4 previews to be generated.

**Comment by nthnca** [comment]
Thanks!
