### ISSUE TITLE
Broken image links when `%\d\d` appears in a directory name

### ISSUE THREAD

**Issue by alexhunsley** [thumbsup/thumbsup#229]
## Bug report

```
Thumbsup version: 2.14.0
Node version: v15.5.1
NPM version: 7.3.0
Operating system: Mac OS 11.1
```

If an input image directory contains a sequence of characters that is in form of a URL encoded character,`%\d\d`, thumbsup doesn't url encode the '%' in resulting hyperlinks, resulting in broken images/thumbnails in the gallery.

For example, if I have a directory of input images that contains `%28` in the dir name, then the generated gallery has broken links to thumbnails (see sample image). This happens because thumbsup makes links to the 'raw' directory name that contains just raw characters %28, but the browser then interprets that `%28` to mean '('.

A solution is for thumbsup to encode anything of form `%\d\d` it sees in directory names (and image names?) to `%25\d\d`.

Note: it's not purely `%` that is the issue -- it has to be followed by two digits for the issue to happen! See again the example image.

I know this is a bit of a weird edge case, but it can come up, because I backed up my flickr a while back which resulted in directory names containing %28, %29 etc (due to bracket chars in my original flickr album names).

Sample gallery showing the issue:

![image](https://user-images.githubusercontent.com/793071/104120666-787e2280-5330-11eb-98b6-3edecefecf8e.png)

**Comment by rprieto** [comment]
Hi @alexhunsley, that's a great find. I think this might happen if the album and/or photo URLs are not URL-encoded. I will try to reproduce locally and then it should be relatively easy to fix.
