### ISSUE TITLE
Error: Could not locate the bindings file. Tried:....

### ISSUE THREAD

**Issue by GeorgiaM-honestly** [thumbsup/thumbsup#233]
Thumbsup version: 2.15.0
Node version: 10.19.0
NPM version: 6.14.4
Operating system: Linux Mint 20.1, XFCE. Installed today, fully updated today
```

What are the error messages?

$ thumbsup --input ~/sshfs/openbsd-images/macro --output ~/sshfs/openbsd-images/macro/tu

/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/compiled/10.19.0/linux/x64/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/binding/node-v64-linux-x64/better_sqlite3.node
    at bindings (/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/index.js:2:18)

**Comment by jaller94** [comment]
This can likely be fixed by running `npm install` again.
Because the better-sqlite3 dependency builds parts of its software specific to your version of NodeJS (= bindings), it needs to be reinstalled every time you update NodeJS on your system..

**Comment by GeorgiaM-honestly** [comment]
Thanks for the response! I Believe I have tried what you have suggested ("_npm install -g thumbsup"_) however I am still encountering the issue.

The longer version is that I started from another fresh install to ensure I'm doing everything as expected. None of the versions have changed.

The initial install ("_npm install -g thumbsup_") finishes, however outputs this:

_npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/thumbsup -> /usr/local/lib/node_modules/thumbsup/bin/thumbsup.js

> better-sqlite3@7.1.2 install /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3
> prebuild-install || npm run build-release_

Attempting to use thumbsup (Note: I am using concurrency 1 due to the remote being over sshfs):
thumbsup --concurrency 1 --input ~/sshfs/path1/path2 --output ~/sshfs/path2-tu

_/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/compiled/10.19.0/linux/x64/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/binding/node-v64-linux-x64/better_sqlite3.node
    at bindings (/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/index.js:2:18)_

Reinstalling ("_npm install -g thumbsup_") finishes, outputting:

_npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/thumbsup -> /usr/local/lib/node_modules/thumbsup/bin/thumbsup.js
+ thumbsup@2.15.0
updated 1 package in 12.187s_

Retrying to use thumbsup results in the same errors as before. I also rebooted the system as a "just in case" and there is no change.

I hope that I am not missing anything obvious?

**Comment by GeorgiaM-honestly** [comment]
I have since moved on to trying the docker container, and I must say it's great! Thank you so much. I can't say this particular issue is resolved, I leave it to you what the next step is.

**Comment by rprieto** [comment]
Hi @GeorgiaM-honestly. If you still have the old setup available, can you please post the contents of this folder?

```bash
tree /usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build
```

If it's empty, I'd like to know if the library can be installed by itself properly:

```bash
mkdir test && cd test
npm init -y
npm install better-sqlite3
tree node_modules/better-sqlite3/build
```

Finally, do you have the standard build tools installed?

```bash
sudo apt-get install build-essential 
```

**Comment by GeorgiaM-honestly** [comment]
Hello,
Thanks for the response. Unfortunately I do not have it available anymore.

**Comment by rprieto** [comment]
No problem. I will close this issue for now, please re-open it if you run into it again.
