### ISSUE TITLE
Docker images for arm64

### ISSUE THREAD

**Issue by dimakuz** [thumbsup/thumbsup#238]
## Docker images for arm64

Hi, I found myself running thumbsup on an arm64 platform recently.
It works great but building the image on target can take a long time and require installation of extra packages.
I would be great if the CI pushed arm64 images on release automatically so they'll be ready for consumption straight away.

**Comment by rprieto** [comment]
Hi, that's a very good idea. Can you please share the changes you had to make to the Dockerfile?

**Comment by dimakuz** [comment]
Luckily everything worked out of the box :)
I've initially built the runtime/build container as node-14 (which took a few minutes) so I've modified thumbsup Dockerfile to base on top of that and not node-12 as the release Dockerfile does.

**Comment by rprieto** [comment]
I'm actually in the process of updating the Docker release process, so it's good timing.

I don't have an Arm environment to test on, could you please check if `ghcr.io/thumbsup/test` works on your system?
This image is published for both Amd64 and Arm64.

**Comment by dimakuz** [comment]
The image itself works fine on both amd64 (Fedora 33, Podman) and arm64 (tested on Raspberry Pi 4 w/ Ubuntu bionic, Docker CE).
I couldn't find any `thumbsup` code there so I just mounted the current master branch and did a node install, (as installed gm/exiftool manually).
I ran it on a small input and it worked!

**Comment by rprieto** [comment]
Hi, I just published new base images with amd64 and amr64 builds.
You can try `docker pull ghcr.io/thumbsup/runtime:node-14`.

Soon I will publish new complete images as well.

**Comment by dimakuz** [comment]
Tested and the images seem to work, built a working thumbsup from the ghcr arm64 images

**Comment by rprieto** [comment]
The new image is out!
Can you please try `docker pull ghcr.io/thumbsup/thumbsup:latest`?

**Comment by dimakuz** [comment]
Confirming it works :)

**Comment by rprieto** [comment]
Thank you for confirming!
