### ISSUE TITLE
Problems with albums and files containing backslashes

### ISSUE THREAD

**Issue by jaller94** [thumbsup/thumbsup#240]
https://github.com/thumbsup/thumbsup/blob/61dc0c588ddb87ef7bd2091a747bd3e188b72496/src/model/file.js#L44

I assume this is supposed to convert Windows folder separators.

Problems:
1. Nested albums don't get properly displayed. `String.prototype.replace` only replaces the first occurrence, if the first parameter is a string.
2. On Unix systems folders may include backslashes. The URLs for albums and files with this character are broken.

**Comment by rprieto** [comment]
Thank you @jaller94 and good catch. You are right this part needs fixing and more testing - I assume a lot can be covered with just unit tests.
