### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by w951wcl** [thumbsup/thumbsup#243]
Thumbsup version: 2.15.0
Node version: 14.16.0
NPM version: 6.14.11
Python: 3.9.2
Operating system: Windows 10.

I am getting a binder error when I try running.

```
npm install -g thumbsup --python="C:\Python\python.exe" --force
npm install better-sqlite3 --python="C:\Python\python.exe"
npm install bindings --python="C:\Python\python.exe"

thumbsup --input "C:\Users\Owner\Google Drive\Gallery" --output "C:\PhotoGallery" 
C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\compiled\14.16.0\win32\x64\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\lib\binding\node-v83-win32-x64\better_sqlite3.node
    at bindings (C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\lib\database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\lib\index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\build\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\compiled\\14.16.0\\win32\\x64\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\node_modules\\better-sqlite3\\lib\\binding\\node-v83-win32-x64\\better_sqlite3.node'
  ]
}
```

**Comment by rprieto** [comment]
Hi, thank you for reporting this. Can you please share the file listing for `C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3\` ? It sounds like it didn't build successfully.

**Comment by w951wcl** [comment]
Thanks for the help.  
I did have problems building this module because I did not have all the MS C++ build tools installed at first.  I am going to try to do a Clean and rebuild if that is an option.
Is this what you are looking for?
Directory of C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\node_modules\better-sqlite3

03/08/2021  01:01 PM    <DIR>          .
03/08/2021  01:01 PM    <DIR>          ..
10/26/1985  02:15 AM                28 .gitattributes
03/08/2021  01:00 PM    <DIR>          .github
10/26/1985  02:15 AM             2,452 .travis.yml
10/26/1985  02:15 AM               282 appveyor.yml
03/08/2021  01:00 PM    <DIR>          benchmark
10/26/1985  02:15 AM               620 binding.gyp
03/08/2021  01:00 PM    <DIR>          deps
03/08/2021  01:00 PM    <DIR>          docs
03/08/2021  01:00 PM    <DIR>          lib
10/26/1985  02:15 AM             1,078 LICENSE
03/08/2021  01:01 PM             2,419 package.json
10/26/1985  02:15 AM             4,792 README.md
03/08/2021  01:00 PM    <DIR>          src
03/08/2021  01:00 PM    <DIR>          test
               7 File(s)         11,671 bytes
               9 Dir(s)  848,705,331,200 bytes free

**Comment by w951wcl** [comment]
Here is the output from the build process:
C:\Users\Owner>npm install better-sqlite3 --python="C:\Python\python.exe"

> better-sqlite3@7.1.2 install C:\Users\Owner\node_modules\better-sqlite3
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=14.16.0 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.1.2 build-release C:\Users\Owner\node_modules\better-sqlite3
> node-gyp rebuild --release


C:\Users\Owner\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  extract_sqlite3
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Users\Owner\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
  win_delay_load_hook.cc
     Creating library C:\Users\Owner\node_modules\better-sqlite3\build\Release\better_sqlite3.lib and object C:\Users\Owner\node_modules\better-sqlite3\build
  \Release\better_sqlite3.exp
  better_sqlite3.vcxproj -> C:\Users\Owner\node_modules\better-sqlite3\build\Release\\better_sqlite3.node
  test_extension.c
  win_delay_load_hook.cc
     Creating library C:\Users\Owner\node_modules\better-sqlite3\build\Release\test_extension.lib and object C:\Users\Owner\node_modules\better-sqlite3\build
  \Release\test_extension.exp
  test_extension.vcxproj -> C:\Users\Owner\node_modules\better-sqlite3\build\Release\\test_extension.node
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Owner\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Owner\package.json'
npm WARN Owner No description
npm WARN Owner No repository field.
npm WARN Owner No README data
npm WARN Owner No license field.

+ better-sqlite3@7.1.2
updated 1 package and audited 130 packages in 50.048s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by w951wcl** [comment]
Sorry for all the comments, but I am now getting this error:
c:\thumbsup-master>thumbsup --input "C:\Users\Owner\Google Drive\Gallery" --output "C:\PhotoGallery"
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'fs-extra'
Require stack:
- C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\bin\thumbsup.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\←[4mthumbsup←[24m\bin\thumbsup.js:3:12)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\bin\\thumbsup.js'←[39m
  ]
}

**Comment by w951wcl** [comment]
I installed fs-extra, moment, insight.
Now I am getting this error:
C:\thumbsup-master>thumbsup --input "C:\Users\Owner\Google Drive\Gallery" --output "C:\PhotoGallery"
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'debug'
Require stack:
- C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\bin\dependencies.js
- C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\bin\thumbsup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\bin\dependencies.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\bin\\dependencies.js',
    'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\thumbsup\\bin\\thumbsup.js'
  ]
}

**Comment by rprieto** [comment]
Hi, all these dependencies should have installed when you ran `npm install -g thumbsup`. You shouldn't have to install `sqlite3` or `bindings` manually either.

I suspect something went wrong in the initial installation if the build tools were not available.

Can you please try to delete `C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup` and rerun `npm install -g thumbsup`?

**Comment by w951wcl** [comment]
npm ERR! code EEXIST
npm ERR! path C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\bin\thumbsup.js
npm ERR! dest C:\Users\Owner\AppData\Roaming\npm\thumbsup
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup\bin\thumbsup.js' -> 'C:\Users\Owner\AppData\Roaming\npm\thumbsup'
npm ERR! File exists: C:\Users\Owner\AppData\Roaming\npm\thumbsup
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2021-03-10T23_11_42_701Z-debug.log
 
Should I use --force?

**Comment by w951wcl** [comment]
Getting there.  It is running now, but the website looks like this:
2015 fall
76 photos
18 Oct 2015 - 18 Oct 2015

2011-02-17 06.53.01.jpg IMG_1999.JPG IMG_2000.JPG IMG_2001.JPG IMG00609-20110701-1306.jpg DSC01595.JPG IMG_2588.JPG IMG_2589.JPG alanLindaMeadow2.JPG alanLindaMeadow.JPG IMG-20120603-00302.JPG CAM00006.jpg CAM00007.jpg CAM00008.jpg IMG_0197.JPG IMG_0198.JPG IMG_0199.JPG IMG_0200.JPG IMG_0201.JPG IMG_0202.JPG IMG_0203.JPG IMG_0206.JPG IMG_0208.JPG IMG_0209.JPG IMG_0211.JPG IMG_0213.JPG IMG_0214.JPG IMG_0215.JPG IMG_0357.JPG IMG_0360.JPG IMG_0363.JPG IMG_3683.JPG IMG_3684.JPG IMG_3685.JPG IMG_3686.JPG IMG_3687.JPG IMG_3688.JPG IMG_3689.JPG IMG_3690.JPG IMG_3691.JPG IMG_3692.JPG CAM00114.jpg IMG_3799.JPG IMG_3800.JPG IMG_3801.JPG IMG_3802.JPG IMG_3958.JPG 480_CarJuly303.JPG alan&linda.gif alan&linda.jpg img221.JPG Linda-and-Alan.jpg Moose Lake Ariel Shot.jpg IMG_4487.JPG IMG_4488.JPG IMG_4489.JPG IMG_4490.JPG IMG_4491.JPG IMG_4492.JPG IMG_4493.JPG IMG_4494.JPG IMG_4501.JPG IMG_4502.JPG IMG_4504.JPG IMG_4505.JPG IMG_4506.JPG IMG_4507.JPG IMG_4508.JPG IMG_4509.JPG IMG_4510.JPG IMG_4511.JPG IMG_4512.JPG IMG_4513.JPG IMG_4514.JPG IMG_4515.JPG IMG_4516.JPG IMG_4938.JPG IMG_4939.JPG IMG_4940.JPG IMG_4941.JPG IMG_4942.JPG IMG_4943.JPG 20180728_082538_001.jpg 20180728_082538_002.jpg 20180728_082540.jpg 20180809_131701.jpg Breeze_180729140301_014.JPG 20180928_192802.jpg corkscrew.jpg Our Lady of Fatima.jpg 20200511_150508.jpg 20200511_150515.jpg Linda 2019.jpg 20200516_141121.jpg 20201008_084733.jpg 20201008_084741.jpg 20201008_130213.jpg 20201008_130218.jpg 20201008_130229.jpg 20201008_154605.jpg 20201008_164120.jpg 20201009_124810.jpg 20201010_164820.jpg 20201010_164830.jpg 20201010_164839.jpg

**Comment by rprieto** [comment]
Do you mean it's text-only? Could you post a screenshot?

**Comment by w951wcl** [comment]
Yes, none of the images are showing, but they are in the media folder.
![Photo Album](https://user-images.githubusercontent.com/80331476/110719370-5e4aae80-81d2-11eb-8dd9-335b0d3790d1.PNG)

)

**Comment by w951wcl** [comment]
![image](https://user-images.githubusercontent.com/80331476/110719492-905c1080-81d2-11eb-9124-81601e832192.png)

**Comment by w951wcl** [comment]
Thanks for your help.  I am a 14 year user of jAlbum.
Need something new!

**Comment by w951wcl** [comment]
So after looking at the HTMl, it has "%5C" instead of "\" in the image path.  Chrome goes not translate it.

**Comment by w951wcl** [comment]
My web server translated that %5C just fine in Chrome.

Thanks

**Comment by rprieto** [comment]
Hi, thanks for all these details. I think this has actually been fixed on the master branch.

If you don't mind, could you try cloning this repository and running Thumbsup from there?

```bash
git clone https://github.com/thumbsup/thumbsup.git
cd thumbsup
npm install 
node bin/thumbsup.js --input ...
```

Otherwise there should be a new version soon!

**Comment by rprieto** [comment]
And if you have any feedback coming from jAlbum, please do share!

If you have Docker installed, there is also Docker image that gives you a one-click setup.

**Comment by w951wcl** [comment]
Thanks, I will try that.  Should I delete C:\Users\Owner\AppData\Roaming\npm\node_modules\thumbsup first?

As for Jalbum, I did not like the navigation and the compression on the photos made the picture fuzzy.

**Comment by rprieto** [comment]
No need to, the commands above will clone the source code in a local folder and run everything from source.
You can keep both in parallel.

**Comment by w951wcl** [comment]
All fixed,  thank you.
Works great.
I just need to install Video Support next.

**Comment by rprieto** [comment]
That's great, thank you for confirming! The new version will be out soon.
