### ISSUE TITLE
Passthrough video encoding

### ISSUE THREAD

**Issue by alandrees** [thumbsup/thumbsup#250]
## Video Encoding Passthrough

Allow for externally generated video ready-to-play as-is without recoding.  

This would mean copying the files in the input directory into their locations in the target output directory.

**Comment by rprieto** [comment]
Hi,

Have you tried the `--video-download` option?
- `resize` will transcode and resize all videos
- `copy` will simply copy the originals as-is
- `symlink` will create symbolic links to the videos in the source folder
- `link` will create HTTP links to the source folder (relative) or any other source (e.g. external URL)

Today there is no "smart" option that only transcodes if the format is not browser-friendly. It's something we can consider adding. We would need to consider
- what happens to supported videos: copy? symlink? link?
- if a similar behaviour is useful for photos

**Comment by rprieto** [comment]
Hi, I'm closing this for now. Please reopen the issue of it doesn't solve the problem.
