### ISSUE TITLE
Missing 2.16.0 docker image?

### ISSUE THREAD

**Issue by gebailey** [thumbsup/thumbsup#251]
## Bug description

According to the [GitHub releases page](https://github.com/thumbsup/thumbsup/releases), there's a `2.16.0` release of thumbsup.  However, attempting to use `docker pull` results in an error:

```
$ docker pull thumbsupgallery/thumbsup:2.16.0
Error response from daemon: manifest for thumbsupgallery/thumbsup:2.16.0 not found: manifest unknown: manifest unknown
```

According to the [tags page on dockerhub](https://hub.docker.com/r/thumbsupgallery/thumbsup/tags?page=1&ordering=last_updated), there doesn't appear to be a `2.16.0` tag available.

## Steps to reproduce

```
docker pull thumbsupgallery/thumbsup:2.16.0
```

**Comment by rprieto** [comment]
Hi, thanks for raising this. The latest version is published directly on Github: `docker pull ghcr.io/thumbsup/thumbsup:2.16.0`.
This was mostly done to avoid rate-limiting issues on DockerHub.

I should update the documentation. Do you think it's valuable to publish to DockerHub as well?

**Comment by gebailey** [comment]
I think there would be some value in publishing to DockerHub as well as GitHub. People might think to check there first, and searching for "thumbsup" in the search bar gives the existing images. (That's assuming it's not much overhead or complexity to publish in both locations).

Either way, thanks for the pointer in the above comment!

**Comment by gebailey** [comment]
Curious why the `2.15.0` image varies depending on where I pull it from?

```
$ docker images
REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
ghcr.io/thumbsup/thumbsup   2.16.0    72e19be96c86   2 weeks ago    341MB
ghcr.io/thumbsup/thumbsup   latest    72e19be96c86   2 weeks ago    341MB
ghcr.io/thumbsup/thumbsup   2.15.0    eff4fe690e11   2 months ago   341MB
thumbsupgallery/thumbsup    2.15.0    2df9940f04ff   3 months ago   334MB
thumbsupgallery/thumbsup    latest    2df9940f04ff   3 months ago   334MB
thumbsupgallery/thumbsup    2.14.0    93c0f96e17e8   9 months ago   333MB
```

If the same image is pushed to two different repositories, I'd expect them to have the same image ID, wouldn't they?

**Comment by rprieto** [comment]
That's a good point, thanks. I'll update the CI pipelines to push to both registries.

The `2.15.0` image was re-built recently to include ARM support, and only pushed to Github. It's based on the exact same commit, but the re-build must have picked up slightly different packages during `apk add`.

**Comment by rprieto** [comment]
That's a good point, thanks. I'll update the CI pipelines to push to both registries.

The `2.15.0` image was re-built recently to include ARM support, and only pushed to Github. It's still based on the same NPM package version, but the re-build must have picked up slightly different packages during `apk add`.

**Comment by paulz1** [comment]
Hmmm... so actually we should use image stored in GitHub registry instead of Docker Hub ?

Should documentation be fixed in this case ?

Also, link from Docker Hub page point to inexisting Github repo (as I understand the docker part is now intergrated into main repo).

**Comment by rprieto** [comment]
Hi. To keep things consistent, I will stop publishing images to DockerHub.

The documentation has been updated.
I have also updated the DockerHub pages to point to the Github registry.
Unfortunately, I couldn't find where to remove the reference to the old (deleted) Github repo.
