### ISSUE TITLE
Support Google Analytics Global Site tag

### ISSUE THREAD

**Issue by lucienve** [thumbsup/thumbsup#257]
Google is encouraging users to switch from Universal (Analytics 3) to Global Site (Analytics 4) tags, which requires changes to the analytics handlebar partial.  Tracking information sent via the global site tag should be backwards compatible with any existing analytics 3 projects, so should be a safe change.

Context: https://support.google.com/analytics/answer/9304153?hl=en&ref_topic=9303319#zippy=%2Cadd-the-global-site-tag-directly-to-your-web-pages

**Comment by rprieto** [comment]
Hi, thank you for your contribution! I just merged your PR (#258) which closes this.
