### ISSUE TITLE
There should be ways to view filenames..

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#265]
Are there ways to view the names of the files in the gallery? I don't see any in the command line options. (I ctrl-f'd for "name".) It would be nice if you could make it display filenames, either under each thumbnail or in the page of the picture when you click on it.

**Comment by rprieto** [comment]
Hi @inhahe. That's true, none of the built-in themes display the file names on the page.
Itzo is right, you can see the in the slideshow by clicking on the Info button.

The best approach would be to create a custom theme that displays the filename under each photo.
You can clone an existing theme to get started, such as https://github.com/thumbsup/theme-cards

**Comment by inhahe** [comment]
I can't find any documentation on how to make a theme... the docs/ directory just has three images in it.

**Comment by rprieto** [comment]
For the documentation, the README points to https://thumbsup.github.io/docs/ .

**Comment by inhahe** [comment]
Ah, sorry I overlooked that.
So, I looked at the page for making themes, but it seems very rudimentary. I'm not sure how to make a theme do what I want. 
I'm thinking of trying adding a `theme/partials/caption.hbs` with the contents `<div>{{filename}}</div>. What's the default theme for thumbsup so I can modify it? Thanks.

**Comment by inhahe** [comment]
Ok, so I found `/usr/local/lib/node_modules/thumbsup/src/website/theme-base/partials` and added `caption.hbs` with with only the contents <div>{{filename}}</div>
It didn't seem to make any difference. I don't know what I'm doing. =/

**Comment by inhahe** [comment]
I just tried it while adding `--theme-path /usr/local/lib/node_modules/thumbsup/src/website/theme-base/` and index.html just contains:

```
No theme applied
This is just the base layout which contains common files such as

Handlebars helpers
Handlebars partials
CSS
```
:`(

**Comment by inhahe** [comment]
Nope, didn't work. =/
I made `/usr/local/lib/node_modules/thumbsup/node_modules/@thumbsup/theme-classic/theme/partials/caption.hbs` with the contents \<div>{{filename}}\</div> and ran thumbsup with ` --theme-path /usr/local/lib/node_modules/thumbsup/node_modules/@thumbsup/theme-classic/theme` and it didn't seem to do anything :/

**Comment by rprieto** [comment]
The idea is to download a basic theme (e.g. https://github.com/thumbsup/theme-classic) and make any changes required. Then you can run thumbsup with `--theme-path /your/custom/theme/path`).

In your case: the classic theme you just downloaded doesn't have the code to render thumbnails. You'll see it refers to a built-in partial called `thumbnails`.

```
{{#each album.files}}
  {{> thumbnail}}
{{/each}}
```

This corresponds to [thumbnail.hbs](https://github.com/thumbsup/thumbsup/blob/master/src/website/theme-base/partials/thumbnail.hbs) You can't change the built-in partial.

Instead you must create `theme/partials/thumbnail.hbs` in your _local_ theme folder. This will override the built-in, and you can make any changes you need.

**Comment by inhahe** [comment]
Thank you, I'll see if I can figure this out.

**Comment by inhahe** [comment]
it looks like I have to tell thumbnail.hbs how to do everything, this is going to be hard. =/

**Comment by rprieto** [comment]
You can copy the original partial (linked above).
Then I think this is what you're after:

```diff
-      data-sub-html="{{meta.caption}}"
+      data-sub-html="{{filename}}"
```

**Comment by inhahe** [comment]
Oh, thanks, I didn't realize that was a link.

**Comment by inhahe** [comment]
Yay! It works! Tysm.

**Comment by inhahe** [comment]
Do I understand correctly that thumbsup by default doesn't provide any way for the viewer to access the original file size? 
How can I modify the classic theme so that, say, when you click on an image while viewing it, it loads the original image with no html/css/js around it?

**Comment by rprieto** [comment]
I think you are looking for `--photo-preview` and `--video-preview`. Please raise a new [discussion thread](https://github.com/thumbsup/thumbsup/discussions) for new questions so it's easier to keep track and everyone can contribute.

**Comment by inhahe** [comment]
Oh, sorry! I just thought it would be inappropriate to raise a whole new thread just for my own ignorance. ;D
But it looks like those options aren't exactly what I want, so I'll raise a new thread:

**Comment by inhahe** [comment]
I just now realized that the `data-sub-html="{{filename}}"` solution isn't showing anything for videos (except animated GIFs), only pictures...?
