### ISSUE TITLE
Error converting HEIC

### ISSUE THREAD

**Issue by scubachristopher** [thumbsup/thumbsup#278]
## Error processing HEIC files
thumbsup:debug photo:large from /Volumes/Pictures Source/Pictures/2019/01/12/20190112-004456837.heic to /Volumes/Gallery/media/large/Pictures/2019/01/12/20190112-004456837.jpg +1ms
  thumbsup:error Error processing Pictures/2019/01/12/20190112-004456837.heic -> media/thumbs/Pictures/2019/01/12/20190112-004456837.jpg
  thumbsup:error Error: spawn magick ENOENT +0ms
  thumbsup:error Error processing Pictures/2019/01/12/20190112-004456837.heic -> media/small/Pictures/2019/01/12/20190112-004456837.jpg
  thumbsup:error Error: spawn magick ENOENT +0ms
  thumbsup:error Error processing Pictures/2019/01/12/20190112-004456837.heic -> media/large/Pictures/2019/01/12/20190112-004456837.jpg
  thumbsup:error Error: spawn magick ENOENT +0ms
  thumbsup:info Processing media (1/176538) [title changed] +5ms
  thumbsup:info Processing media (2/176538) [title changed] +0ms
  thumbsup:info Processing media (3/176538) [title changed] +0ms
  thumbsup:info Finished [title changed] +5ms
  thumbsup:info media/thumbs/Pictures/2019/01/11/20190111-110108345.jpg [title changed] +0ms
  thumbsup:debug photo:thumbnail from /Volumes/Pictures Source/Pictures/2019/01/11/20190111-110108345.heic to /Volumes/Gallery/media/thumbs/Pictures/2019/01/11/20190111-110108345.jpg +11ms
  thumbsup:trace magick "convert" "/Volumes/Pictures Source/Pictures/2019/01/11/20190111-110108345.heic[0]" "/var/folders/5n/4yn3z5b512v4pqd9klcdg4lm0000gq/T/tmp-14001-AC14Hc6IsQZq-.jpg" +23ms
  thumbsup:error Error processing Pictures/2019/01/11/20190111-110108345.heic -> media/thumbs/Pictures/2019/01/11/20190111-110108345.jpg
  thumbsup:error Error: spawn magick ENOENT +15ms
  thumbsup:info Processing media (4/176538) [title changed] +10ms
  thumbsup:info Finished [title changed] +0ms
  thumbsup:info media/small/Pictures/2019/01/11/20190111-110108345.jpg [title changed] +1ms
  thumbsup:debug photo:small from /Volumes/Pictures Source/Pictures/2019/01/11/20190111-110108345.heic to /Volumes/Gallery/media/small/Pictures/2019/01/11/20190111-110108345.jpg +10ms
  thumbsup:error Error processing Pictures/2019/01/11/20190111-110108345.heic -> media/small/Pictures/2019/01/11/20190111-110108345.jpg
  thumbsup:error Error: spawn magick ENOENT +1ms
  thumbsup:info Processing media (5/176538) [title changed] +0ms
  thumbsup:info Finished [title changed] +0ms

MacOS 11.6, Air M1, 16GB RAM
Thumbsup 2.16.0

**Comment by rprieto** [comment]
Hi @scubachristopher . I see

> thumbsup:error Error: spawn magick ENOENT +1ms

HEIC support requires ImageMagick version 7 or above.
Can you please check that you have it installed and in your path?

Note: this is required _in addition_ to GraphicsMagick. GM is used for all image processing because it's faster and more resource-friendly, but it doesn't support HEIC.

**Comment by gebailey** [comment]
> HEIC support requires ImageMagick version 7 or above. Can you please check that you have it installed and in your path?
> 

I use the docker container `thumbsupgallery/thumbsup` and I see `gm` in the path, but not `im`. Is it included in the docker container and I just didn't see it?  I've also run into HEIC files on occasion.

**Comment by rprieto** [comment]
Hi @gebailey. The official image should definitely have ImageMagick built-in. The binary is called `magick`. Can you please check if you see it on your copy of the image? Are you running into issues too?

**Comment by gebailey** [comment]
> Hi @gebailey. The official image should definitely have ImageMagick built-in. The binary is called `magick`. Can you please check if you see it on your copy of the image? Are you running into issues too?

Yes, it does have ImageMagick; apologies for the confusion. I'm having problems with `.jfif` files not being processed and I was confusing the two file types.

**Comment by scubachristopher** [comment]
That worked -- thank you!
