### ISSUE TITLE
Please add "mpg" to the list of supported (input) video extensions 

### ISSUE THREAD

**Issue by uglow** [thumbsup/thumbsup#280]
## Add "mpg" as a supported video extension

In `src/components/index/glob.js`, there is this line:

 ```
const VIDEO_EXT = ['3gp', 'avi', 'flv', 'm2ts', 'm4v', 'mkv', 'mp4', 'mov', 'mts', 'ogg', 'ogv', 'webm', 'wmv']
```

If you can add `'mpg'` to this list, it will allow *.mpg video files to be processed by ffmpeg. I have tested this with the ffmpeg version that is in the docker container, and it works.

Some of my older videos use the MPG format, and I'd like to see them on my website. 

Thanks for producing such a useful tool!

**Comment by rprieto** [comment]
Hi, thank you for raising this. I agree it's a good idea, it definitely should be in there. I will add `.mpeg` as well.
