### ISSUE TITLE
--download-photos vs --photo-download?

### ISSUE THREAD

**Issue by phripley** [thumbsup/thumbsup#285]
This I believe is a comment on typos in the thumbsup documentation.  Or perhaps I am not understanding the documentation in which case it is request for clarification in the documentation.

The [cheat sheet](https://thumbsup.github.io/docs/3-configuration/cheat-sheet/) mentions the output setting setting `--download-photos`.

When I look at [the output settings page](https://thumbsup.github.io/docs/3-configuration/output-settings/) the only mention of `--download-photos` is inside the description for the `--watermark` setting.

But the output settings page does have documentation of `--photo-download `.

`--photo-download` seems to give me the expected result.  I'm guessing that `--download-photos` is either an alias, a typo or an older syntax.

It appears that the same issue pertains to `--download-videos` vs `--video-download`

**Comment by rprieto** [comment]
Hi, thank you for raising this. You are right ` --download-photos` and ` --download-videos` are now deprecated. I just updated the documentation to remove these old references.

I also just added a system to re-build the cheatsheet automatically every month, so this shouldn't happen again!

Thanks.
