### ISSUE TITLE
new release for google analytics update

### ISSUE THREAD

**Issue by riznob** [thumbsup/thumbsup#316]
## new release for google analytics update

Please create a new release so users can take advantage of [this change](https://github.com/thumbsup/thumbsup/pull/258). This was merged to `master` since the latest release.

**Comment by cernoch** [comment]
Indeed! @rprieto, are you the maintainer?

**Comment by rprieto** [comment]
Hi, sorry for the slow update!
Version 2.17.0 is now published to npm, with the corresponding Docker image at `ghcr.io/thumbsup/thumbsup:2.17.0`.

**Comment by rprieto** [comment]
Update: there was an issue with tag `2.17.0`. The Docker image includes the latest version of GraphicsMagick, which didn't remove EXIF metadata as expected. This is fixed in `2.17.1`. If necessary, please delete and rebuild the affected thumbnails.
