### ISSUE TITLE
Disable download of images via UI

### ISSUE THREAD

**Issue by georg90** [thumbsup/thumbsup#323]
## Disable download of images

It would be great if we can add an option to disable download of originals / resized images. For this use case we do not need any protection of people right-clicking an image and download but rather disable the download button in the slideshow. 

Workaround: We set the `--photo-download` option to `link` and added a random prefix via `--link-prefix`. The download links are broken and the images cannot be downloaded by clicking a button.

How can I improve the user experience here?

**Comment by rprieto** [comment]
Hi. This can be controlled in the `lightgallery` options:

```js
 $("#media").lightGallery({
          thumbWidth: 80,
          controls: true,
          loop : false,
          download: true,  // <— false
          counter: true,
          videojs: true,
          fullScreen: true,
          zoom: true
        });
```

These default values are set by each theme.
The easiest way to change it is to copy the theme locally on your PC, update the value, and then run Thumbsup with `--theme-path <dir>`.

You can find more options in the official docs: https://www.lightgalleryjs.com/docs/settings/

**Comment by georg90** [comment]
Hey @rprieto !
Leaves no questions unanswered! Thank you!
