### ISSUE TITLE
Gallery generated successfully!  │ │  1 albums, 0 photos, 0 videos 

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#343]
## Bug description

I have a directory with 2456 files and 18 subdirectories with further files in them.

Here are some examples of the files and subdirectories under /home/inhahe/pics:

drwxrwx---  2 inhahe vboxsf     4096 May 30 15:50 'Zdzisław Beksiński'
-rwxrwx---  1 inhahe vboxsf    11168 May 30 22:46  zebu1.jpg
-rwxrwx---  1 inhahe vboxsf    45334 May 30 22:46 'zen wu one, china.webp'
-rwxrwx---  1 inhahe vboxsf    23151 May 30 22:46  zm74mv.jpg
-rwxrwx---  1 inhahe vboxsf  1826186 May 30 22:46 'zRo5tOp8T3ukbzmk89n7_2 girls 1 trustfall.gif'
-rwxrwx---  1 inhahe vboxsf  5229369 May 30 22:46 'zUutCAxHQhmh0ZmeTT94_tower of rafts.gif'

## Steps to reproduce

I entered the following command according to https://thumbsup.github.io/docs/2-installation/docker/:
`sudo docker run -t -v "$(pwd):/home/inhahe/" -u $(id -u):$(id -g) ghcr.io/thumbsup/thumbsup thumbsup --input /home/inhahe/pics --output /home/inhahe/pics2`

The result was 1 albums, 0 photos, 0 videos processed.

I noticed that if I specify an output directory that's a subdirectory of the input directory and then run the command again, the number of albums and photos processed increases exponentially each time I run it. So apparently it's detecting the files in the output subdirectory but not the rest of the files.

Update: I read up on the docker  run syntax and changed the command to `sudo docker run -t -v "/home/inhahe:/home/inhahe" -u $(id -u):$(id -g) ghcr.io/thumbsup/thumbsup thumbsup --input /home/inhahe/pics --output /home/inhahe/pics2`

and now it recognizes all the files, but again I get the `Unexpected error Cannot read properties of undefined (reading 'FileModifyDate')` that I posted about in another issue.

**Comment by rprieto** [comment]
Hi. Glad you solved the first issue (indeed seems to be a Docker mount issue).

For the second  issue, can you please run it again with `--log debug` and share the output? Is it happening with one file specifically?

**Comment by rprieto** [comment]
Hi. Glad you solved the first issue (indeed seems to be a Docker mount issue). I will close this issue and we can troubleshoot in the one one you raised.
