### ISSUE TITLE
All video files are missing in the destination

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#344]
## Bug description

I have 45 mp4 files and 2 webm files in my input directory (including all subdirectories)
There are no mp4 or webm files the output directory or any of its subdirectories.
When I click on a video in the gallery in the browser, it says "The media could not be loaded, either because the server or network failed or because the format is not supported."
When I click the download icon, it says "Your file couldn’t be accessed / It may have been moved, edited, or deleted. / ERR_FILE_NOT_FOUND".
The jpg thumbs for the video files are present.
The problem is not the filenames this time because this was run after running detox -r on the directory.

When I look at thumbsup.log, I see a ton of errors like this for different video files:
```
2023-05-31T14:36:00.992Z thumbsup:error Error processing peacock.mp4 -> media/large/peacock.mp4
2023-05-31T14:36:00.992Z thumbsup:error Error: ffmpeg exited with code 1

```
I tested ffmpeg just to make sure it works, by doing `ffmpeg -i VAIRO_CK_14._NFTart-https_t.co_FiOrn0SVcO_1625701013079588865_.mp4 VAIRO_CK_14._NFTart-https_t.co_FiOrn0SVcO_1625701013079588865_.webm'

It worked fine.
## Steps to reproduce

thumbsup --input pics --output pics2, where pics is a directory structure containing a couple thousand files, a few of them mp4's and few webm's.

**Comment by inhahe** [comment]
I just saw in https://github.com/thumbsup/thumbsup/issues/339#issuecomment-1537546344 that the problem is that it's supposed to use ffmpeg 5.1.
So I did brew install ffmpeg$5, that worked
and I followed the instruction to make it first in my path, `echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/ffmpeg@5/bin:$PATH"' >> ~/.profile`
But still, when I run `ffmpeg` it reports that it's version 6.0.
I even tried closing and relaunching the command terminal.
How do I make it use ffmpeg 5?

**Comment by inhahe** [comment]
n/m I found out that I had to do `. ~/.profile`, it seems to be working now.

**Comment by rprieto** [comment]
Thanks for raising this, and for the troubleshooting. I'm glad you got it to work. I'll try to add ffmpeg 6 support soon.
