### ISSUE TITLE
Major missing feature: direct linking to pictures, that would allow sharing

### ISSUE THREAD

**Issue by ghost** [thumbsup/thumbsup#35]
I was hot for thumbsup, until I realized, there is no link to pictures, directly, and pictures are very hard to be shared on social networks.

**Comment by rprieto** [comment]
Hi @rmaddox. You *can* actually deep link to pictures, but maybe not in the way you want.

If you open the slideshow, simply right-click on the "download" button (top right) and copy the link to your clipboard. For example on http://rprieto.github.io/thumbsup/photos.html

![download button](https://cloud.githubusercontent.com/assets/189105/11682376/81e25512-9eb8-11e5-87f4-a49a2a26bef2.png)

It won't deep-link to the photo in the context of the album though, it's a link to the full-size origin image. Is that OK, or would you need to deep-link within an album (so people can press left/right to navigate)?

**Comment by rmaddox** [comment]
Yes, I know directly it is possible, but user would not come to the website, and would not be able to browse back to albums or to main website. It looks good, but thumbsup is not at all social networks friendly.

**Comment by rprieto** [comment]
Fair enough. Thumbsup uses `lightgallery` to browse photos/videos, I'll see if there's anything to deep link to a particular photo.

**Comment by rmaddox** [comment]
Today's world is about marketing to social networks. If you ask me, for each image, there shall be HTML file, and such file shall contain something like:

```
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>{$page_title}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel=icon href="{$faviconico}" sizes="60x60" type="image/png"/>

    <!-- Standard Meta Tags -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="generator" content="{$generator}"/>
    <meta name="author" content="{$page_author}"/>
    <meta name="keywords" content="{$page_keywords}"/>
    <meta name="description" content="{$page_description}"/>
    <!-- Standard Meta Tags -->

    <!-- Google Schema.org -->
    <meta itemprop="name" content="{$page_title}" /> 
    <meta itemprop="description" content="{$page_description}" />  
    <meta itemprop="image" content="{$page_ogimage}" /> 
    <!-- Google Schema.org -->

    <!-- Facebook Open Graph -->
    <meta property="og:title" content="{$page_title}"/>
    <meta property="og:type" content="{$page_ogtype}"/>
    <meta property="og:url" content="{$current_url}"/>
    <meta property="og:image:url" content="{$page_ogimage}"/>
    <meta property="og:site_name" content="{$areas_name}"/>
    <meta property="og:description" content="{$page_description}"/>
    <meta property="fb:admins" content="{$fb_admins}"/>
    <!-- Facebook Open Graph -->

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@{$twitter_user}"/>
    <meta name="twitter:creator" content="@{$twitter_user}"/>
    <meta name="twitter:title" content="{$page_title}"/>
    <meta name="twitter:description" content="{$page_description}"/>
    <meta name="twitter:image" content="{$page_ogimage}"/>
    <!-- Twitter Card -->
```

This allows proper sharing to Twitter, Google, Facebook, and other services.

**Comment by rprieto** [comment]
I can see how posting photos to social networks could be useful, we just have to keep in mind it's not the *only* use. I'm happy to add features to help if it's doesn't add too much complexity. Some ideas:

- `thumbsup` will always keep a slideshow, as browsing 1 page per image would be much slower & cumbersome. But maybe there could also be an additional page just for sharing. What would be on that page? How do you navigate to it? Does it have links to the rest of the gallery?
- if we do have a separate page, social tags make sense. It would be hard to handle all 20 tags you suggested (where do you get the data from?) but we'd probably cover 90% of typical use cases by just reading Image URL and Caption (that we already have) and writing the matching Google/Facebook/Twitter tags.

**Comment by rmaddox** [comment]
I agree that thumbsup should remain just the same like it is now, totally. Browsing one page per picture would be slow.

On the gallery, or pictures, there shall be implemented simply 3 buttons, Twitter, Facebook, Google Plus. Meta tags would ensure that correct picture and link is used in sharing. The sharing buttons would not share the picture itself, rather the single HTML page for the picture. Let us say that is directory /images

For sharing, there shall be single pages for each picture, with the meta tags, as suggested in such HTML file.  Let us say, that such HTML file is named: "IMG001.jpg-My adventure in Africa.html" as file names better for SEO, should represent titles of pictures. The HTML file should show the picture itself, and the row of other pictures in the album. Any click on those pictures in the row, or on the main picture, should bring the user to the chosen picture from the row, in the file /images, something like /images/#img1 where user could simply continue where he was directed. He would not be any more on the HTML file, but in main album. The single HTML page, would again have the 3 buttons for sharing.

The 20 tags are easy to handle, they are repeatable, titles could be taken from image meta tags, as shortened from descriptions in the meta tags, and could be also used for descriptions in the full size. The picture link should be clear. The URL for the page, would be the single page. Each single page would have those meta tags.

The thumbsup could become number #1 gallery software, with superb SEO features. I am willing to pay US $100 for such development.

**Comment by rprieto** [comment]
Closing this because there hasn't been any activity.

Generating a page per image is possible but would be a big change, especially if all themes need to support it. We can revisit this if there's more demand.

In the meantime, themes can support direct linking (without Facebook tags) by using a URL hash like `album.html#image1`. Lightgallery has a plug-in that supports this.
