### ISSUE TITLE
link-prefix ignores '..'

### ISSUE THREAD

**Issue by ccvca** [thumbsup/thumbsup#351]
## Bug description
Following path structure:
```
[vHost]/Orig/MyFolder/Image.jpg
[vHost]/gallery/index.html
```
When specifying `--link-prefix="../Orig/"` the resulting path in the template removes all '../'.

Expected behaviour: `../Orig/MyFolder/Image.jpg` which results in `https://example.com/gallery/../Orig/MyFolder/Image.jpg`
Bug behaviour: `Orig/MyFolder/Image.jpg` which results in `https://example.com/gallery/Orig/MyFolder/Image.jpg`

I suspect that the "relative" keyword is causing the problem here: https://github.com/thumbsup/thumbsup/blob/f7634dbfdfaf850d7657bf5be6b6deee61869335/src/website/theme-base/partials/thumbnail.hbs#L46

## Steps to reproduce

```
docker run -t \
  -v "[vHost]/Orig:/data/Orig:ro" \
  -v "[vHost]/gallery:/data/gallery" \
  -v "/etc/localtime:/etc/localtime" \
  -u 0:0 \
  --rm \
  ghcr.io/thumbsup/thumbsup \
  thumbsup --input /data/Orig --output /data/G \
  --albums-from "%path/{dddd-DD-MMM}" \
  --include-photos true \
  --photo-download link \
  --video-download link \
  --large-size 1080 \
  --photo-quality 80 \
  --embed-exif true \
  --album-previews spread \
  --link-prefix "../Orig" \
  --concurrency 4
```

Version: "latest" -> Tag 2.17.1

**Comment by rprieto** [comment]
Thanks for raising this. Indeed it looks like a bug.

The name vHost suggests you might be hosting a web server. In the meantime could you use a HTTP link prefix such as `--link-prefix http://vhost/Orig`?

**Comment by ccvca** [comment]
`--link-prefix` is indeed my current work around.

**Comment by rprieto** [comment]
Hi @ccvca. This is now fixed on the main branch. It will be part of the next release.
Thanks for reporting it!
