### ISSUE TITLE
Integrate thumbsup with photoprism to allow searching of images

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#373]
## thumbsup-photoprism

This is kind of a big request, but I think it would be really neat. I'm half thinking about trying to do it myself, but really I think I lack the expertise. 
photoprism ( https://github.com/photoprism/photoprism ) is an open-source Linux an program that uses AI to add tags to your images and lets you search them using a web interface. If thumbsup could adopt the core code from photoprism to (optionally, as I guess this would require the user have PHP, a DBE, etc. set up) allow a search feature in index.html for all the images, that would be awesome.

**Comment by rprieto** [comment]
It's an interesting idea. Unfortunately it's not achievable because neither is made to integrate that way.

Searching could be added in other ways. It could be client-side (in browser) for simple use cases, or introducing a new server side option (SQLite FTS or ElasticSearch).

This is already tracked as #310.

**Comment by inhahe** [comment]
This is a distinct feature request from #310. That just asks for a way to search by filename. This is more of an intelligent search based on the images'/videos' contents. It would use AI to tag the images with relevant information for searching.

It's true photoprism isn't designed in a way that can really be integrated with thumbsup, I was hoping you could just use the relevant parts of their code and make up the rest... I guess realistically the only relevant part of their code would be the AI model itself. I guess it would be a lot of work. =P
