### ISSUE TITLE
Switch to Sharp instead of GraphicsMagick

### ISSUE THREAD

**Issue by rprieto** [thumbsup/thumbsup#5]
Switch to https://github.com/lovell/sharp for better performance :)

Need to wait until the Windows support is complete (https://github.com/lovell/sharp/issues/19).

**Comment by lovell** [comment]
Hello, sharp v0.10.0 is now available and adds [support for Windows](https://github.com/lovell/sharp#windows).

**Comment by rprieto** [comment]
That's great news, thanks a lot!

**Comment by rprieto** [comment]
Closing for now. This would have to be implemented in https://github.com/thumbsup/downsize, checking that it supports all the use cases, e.g. applying EXIF rotations, animated gif, etc (see integration test suite).
