### ISSUE TITLE
filesystem links original-photos

### ISSUE THREAD

**Issue by ReSearchITEng** [thumbsup/thumbsup#61]
This might be considered an enhancement, but from space usage p.o.v. a bug.
When original-photos is set to true, is there a need to copy the files to another folder?
One suggestion is to have an option to create links to them instead of duplicating GBs of pictures.
PS: It was noted that even with original-photos, also duplicated the pictures in two places: originals and large, therefore 3 times the same pics.

**Comment by rprieto** [comment]
That's a good idea for an enhancement, with a new configuration setting. The original use case was that I wanted to upload the full `output` folder somewhere, so copying originals was simpler. So I have:

- originals, which i need to be very careful about
- the output folder, which is self-contained and I could always delete and rebuild from scratch (although it would take time)

What use case do you have in mind?

- if it's for local browsing only, a simple symlink would to the job
- it you need to upload the galleries, we need to think about how relative links work. Do you provide the absolute path to where originals are hosted?

Regarding `large` and `original`, they should be different. By default the large version is only 1000px wide.

**Comment by rprieto** [comment]
Quick update that I've started working on this, and there will soon be an option to have originals point directly to the source location (or to another location if you already have them on a HTTP server somewhere for example).

**Comment by multiscan** [comment]
This is very good news in my case.

It is true that the original design makes perfect sense
 if you generate your gallery from a local computer where you keep the original and then, as you say, upload the generated static web site to the web server. 

In my case, I have a huge amount of pictures to share internally, and the generation is done directly on the web server. Hence, avoiding the duplicate is very welcome.

Thank you very much.

**Comment by rprieto** [comment]
No problem, I hope to finish in a few days. Will it work for your use case if the albums simply reference the originals using a path prefix? For example:

- Photo path inside the input folder:   `holidays/IMG_1234.jpg`
- New command line flag: `--download-path-prefix "../../../../originals"`
- Download link: `<a href="../../../../originals/holidays/IMG_1234.jpg">`, in which case the originals aren't even copied to the output folder

The path prefixes can be either relative paths, absolute paths, or even URLs.

**Comment by rprieto** [comment]
The pull request on #66 should implement this via several new flags. There's more documentation on the PR itself.

```
 --download-photos       Target of the photo download links  [choices: "large", "copy", "symlink", "link"] [default: "large"]
 --download-videos       Target of the video download links  [choices: "large", "copy", "symlink", "link"] [default: "large"]
 --download-link-prefix  Path or URL prefix for linked downloads  [string]
```

Do you want to try it out (branch is called `download-options`) see if it works well for you?
