### ISSUE TITLE
error on first run

### ISSUE THREAD

**Issue by hanskoff** [thumbsup/thumbsup#65]
Hi I see an error  :/

what's wrong?

$ thumbsup --input ./funy --output ./gallery

Finding media       [=========================] 8/8 done
Updating database   [-------------------------] 0/8 /Users/jankowalski/.nvm/versions/node/v7.7.2/lib/node_modules/thumbsup/src/index.js:30
        fileCollection = dbFiles.map(f => new File(f, opts))
                                ^

TypeError: Cannot read property 'map' of undefined

**Comment by hanskoff** [comment]
ok I was missing some dependecies

**Comment by rprieto** [comment]
Hi, this looks the same as #62. Of you've upgraded from v1 to v2 it should warn you to delete `metadata.json`, but there's a bug that crashes instead. I'll publish the fix today.
