### ISSUE TITLE
New feature: --filter-input

### ISSUE THREAD

**Issue by rprieto** [thumbsup/thumbsup#68]
What about the idea of an input filter? Only the files that pass the filter would be processed and resized, and appear in the galleries. It could be a new CLI argument, parsed with https://www.npmjs.com/package/safe-eval:

```bash
--filter-input "file => file.meta.favourite === true"
```

Or maybe passing the path to a Node.js module:

```bash
--filter-input-path ~/filter.js
```

And the filter script can look like:

```js
// filter.js
module.exports = (file) => {

  // based on the file path
  return file.path.match(/holidays/)
  
  // or based on metadata
  return file.meta.favourite === true
  return file.meta.rating > 4
  return file.meta.keywords.include('holidays')

}
```

**Comment by rprieto** [comment]
Cleaning up the issues, will re-open if this becomes a priority.

**Comment by seanakabry** [comment]
Is `include()` a typo? Should it be `includes()`?

(Just in case this saves Javascript novices like me a bit of time!)

**Comment by rprieto** [comment]
Hi. Yes you’re right the correct array syntax is `.includes()`.

However this issue was a feature idea, which is not yet implemented.

For now you can’t filter the input, but you can create custom albums like `--albums-from "file://mapper.js"`.
