### ISSUE TITLE
Custom paths for templates / themes

### ISSUE THREAD

**Issue by jesperrasmussen** [thumbsup/thumbsup#69]
## Feature request

First of all, thanks for thumbsup, it's really speedy compared to what I used previously :) 

I'm currently setting up a personal photogallery, and even though I enjoy the simplicity of thumbsup, I wanted to do some more advanced templates, as my current gallery has a specific markup and I wanted to use a specific lightbox for displaying the images. 

I looked into the thumbsup code, and noticed that it's not possible to define templates/themes outside of the standard ones provided by default, and so I've created a fork, adding a few options, to override where thumbsup looks for templates / themes, as well as adding custom files to the public folder - to give full control of rendering.

I'm unsure if this is something you're interested in? If so, I'll make a PR for it, with the changes I'm currently running with :)

**Comment by rprieto** [comment]
Hi, that's great! I'm definitely interested.

There was some discussion in #64 about it, and it would be great to have a way to create themes more easily. I was also getting started on extracting the built-in themes to their own repo (e.g. https://github.com/thumbsup/theme-mosaic) to make the core/theme interface more robust... so it's great timing.

What did you have in mind? I really like the idea of being able to add files to `./public` too! Some other aspects I've been wondering about:

- should all themes be rendered with Handlebars by the engine, or should they have full control of how they render? Enforcing Handlebars could have some advantages, e.g. we can pre-load a lot of helper and partials.
- how should themes be loaded? Is it any path with a standard folder structure, or are they `npm` packages - that you can use locally with `npm link` if you want?
- what does the structure look like? E.g. simply `public` and `template` folders?
- what's the best way to communicate data model changes?

Also great to hear you're enjoying thumbsup, let me know if you think of other features! I just saw you created https://github.com/jesperrasmussen/ansible-role-thumbsup which looks very useful. Let me know if you want to make this an official Ansible playbook, and I could make you the admin of something like https://github.com/thumbsup/ansible.

**Comment by jesperrasmussen** [comment]
Sorry about the late response, had a vacation and a young kid stealing all my time ;)

However: Great!

First off, the changes I've made to accomodate my needs have been fairly simple. Right now, I've just added a few options to allow for a custom path, where thumbsup will look for the theme, as well as the custom public folder. This was done to have full control of the images/CSS in the final rendered version, and it's probably not the most complete way of adding the functionality into thumbsup.

In regards to your considerations, here's my 2 cents:

  * Keeping Handlebars as rendering engine will simplify template creation, as the tags are given - meaning anyone can just create a new theme by using the predefined tags. The downside of course, is that it keeps theme creators from having full flexibility in creating new themes.
  * My solution just adds simple path customization - which means the folder structure of the custom paths will have to be the same as the built in ones. It's not the perfect solution, it's just a simple enough one to get me the custom things I wanted :)
  * Yep
  * I'm guessing in case you want to open up thumbsup to themecreators in general, will probably require a certain level of documentation around the data model surrounding albums and images. It's hard to communicate changes to that in a programmatic way (I think, at least) - so unless you want to add versioning to the rendering mechanism, I'd guess the best way would be through documenting the models.

Regarding the Ansible role: I'm currently using that, as I have a NAS storing all my images - and I want `incron` to monitor some specific folders for new images, to allow for adding them to my online gallery automatically, once they are backed up to my NAS as part of my simple photo workflow. If you'd like, I'd be more than happy to assist in that part, adding the automation parts I've done to an official Ansible role :)

Anyway, the customized changes I've already made are available in my fork of thumbsup, as shown here:

https://github.com/jesperrasmussen/thumbsup/commits/master

My own photogallery, based on thumbsup, is running at: http://photos.jesperrasmussen.com if you want to have a look. Currently it doesn't scale quite properly on smaller devices though ;)

**Comment by rprieto** [comment]
Hi @jesperrasmussen, I hope you're still enjoying thumbsup. Custom themes have finally landed in version `2.4.0`. As you suggested, they let you specify Handlebars templates, styles and extra static files. The docs are available at https://thumbsup.github.io/docs/4-themes/create/.

Let me know if you have any feedback! I'll close this issue, but feel free to join the latest conversation at https://github.com/thumbsup/thumbsup/issues/97.
