### ISSUE TITLE
Gallery Fail if No Sub-Folders in Source Folder

### ISSUE THREAD

**Issue by jbrice** [thumbsup/thumbsup#70]
## Bug report
```
thumbsup V2.0.1
npm 4.2.0
node v7.10.1
Operating system: Ubuntu Server 16.04
```

About the bug...
- Is the behaviour different from expected? yes
- Can you provide steps to reproduce the issue? yes

This a newcomer's simplest possible test of thumbsup.

1.  Put a selection of image files in a folder (herinafter "source_folder").
2. Run thumbsup thus: `thumbsup --input /full/path/to/source_folder --output /somewhere/temp`

Result is that the output includes a gallery file called `.html` and a corresponding link to`.html` in `index.html`. The generated gallery does not work when loaded onto a server as the server doesn't recognise `.html` as a valid HTML file. (I nearly walked away from thumbsup at this point.)

It looks as if the code does not cope with most basic case where there are images in the source folder passed to thumbsup. 

Possible solutions? Maybe use the source folder name if images are found in the source folder rather than in a sub-folder?

**Comment by rprieto** [comment]
Hi @jbrice, thanks for the bug report! That's definitely not great, it should work out of the box for a simple case like that. Thanks for not walking away, hopefully will be fixed in the next few days :)

**Comment by rprieto** [comment]
Do you mind adding some detail about what exactly you're seeing? I ran a test, and while I agree the result isn't very pretty I'm not seeing any errors. What I see is this, so effectively a Home album with 1 sub-album called `.` (current folder).

![image](https://user-images.githubusercontent.com/189105/28460606-1f2c2320-6e56-11e7-993d-e808787dcebd.png)

This should be easy to fix by attaching the images to the home gallery instead, but I want to make sure I'm fixing the right thing.

**Comment by rprieto** [comment]
Edit: OK I was running locally on macOS, and Chrome is happy to load the hidden file called `.html`. I can see how that would be an issue on a web server.

**Comment by jbrice** [comment]
Logically any images in the source/home directory should be part of `index.html`, although I don't know enough about how things are coded to know if that is a simple option or a total nightmare.
Otherwise a "root" album needs to be created and the gallery "root" is already labelled as "Home" in some themes, so maybe that is the way to go,

**Comment by rprieto** [comment]
Attaching the images to the root/home gallery shouldn't be too complicated, I'll keep you updated.

For the 20min, is that good to bad? The main advantage is next time you run it, it should only take about 5sec.

**Comment by rprieto** [comment]
Update: all fixed now, I'll run some more tests and try to publish a new version soon.

**Comment by rprieto** [comment]
@jbrice do you mind trying version `2.1.0` and let me know if that works for you?

**Comment by jbrice** [comment]
Yes - that works for me. Repeating initial tests now show thumbsup behaving as I would expect. Many thanks!

**Comment by rprieto** [comment]
No problem! Please let me know if you have any problems or ideas for new features.
