### ISSUE TITLE
Incorrect QuickTime Tag in getDate

### ISSUE THREAD

**Issue by possebaer** [thumbsup/thumbsup#71]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.1.0
exiftool version: 10.55
```
The exiftools tags that are read from quicktime formats like mp4 videos
contains a tag called "CreateDate" for the creation date of the content:
see https://sno.phy.queensu.ca/~phil/exiftool/TagNames/QuickTime.html -- QuickTime MovieHeader Tags

In the function getDate in src/model/media.js a wrong Tag "CreationDate" is filtered for in Quicktime
content -- therefore not the correct content date but the file date is returned.

I don't know if this tag is named differently in other sources, but for my mp4's "CreateDate" is the 
correct one.

**Comment by rprieto** [comment]
Hi @possebaer, thanks for the detailed issue & solution! I've seen `CreationDate` as well so we should probably try both values. I'll push a fix out soon.

**Comment by rprieto** [comment]
Hi, so I had a look at existing video collections, and my metadata looks like this:

```js
[
  {
    "SourceFile": "2014-04-01 10.55.07.mov",
    "ExifTool": {
      "ExifToolVersion": 10.2
    },
    "File": {
      "MIMEType": "video/quicktime"
    },
    "QuickTime": {
      "CreateDate": "2014:03:31 23:54:40",
      "TrackCreateDate": "2014:03:31 23:54:40",
      "CreationDate": "2014:04:01 10:54:40+11:00",
    }
  }
]
```

It looks like `CreationDate` is a tag that also includes the timezone offset... however it might be iPhone specific for example. If you look at your `metadata.json`, can you see `CreationDate` at all?

Timezones is an area where Thumbsup needs work, to be able to render dates more accurately. In the meantime I'm happy to fallback to `CreateDate` if `CreationDate` does not exist.
