### ISSUE TITLE
Some videos prevent the gallery from being generated

### ISSUE THREAD

**Issue by tribut** [thumbsup/thumbsup#76]
## Bug report

```
Thumbsup version: 2.1.0
Node version: 6.11.4
NPM version: 3.10.10
Operating system: Debian Stretch
```
When the thumbnail for a video cannot be generated, an error is thrown and the gallery is not generated. I would have expected the video to be skipped:

~~~~
$ thumbsup --input in --output out

Finding media       [=========================] 1/1 done
Updating database   [=========================] 1/1 done
Processing photos   [=========================] up to date
Processing videos   [========-----------------] 1/3 doneUnexpected error
{ Error: Command failed: gm identify: Unable to open file (/home/www-bilder/test/out/media/thumbs/P1080893.jpg) [No such file or directory].
gm identify: Request did not return an image.

    at ChildProcess.onExit (/home/www-bilder/.local/lib/node_modules/thumbsup/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) code: 1, signal: null }
~~~~

This is probably similar to #75 

Here is a video to reproduce: https://wolke.tribut.de/s/FEswIpxRbme78lY

Note that ffmpeg can read the video, it just does not generate an image:

~~~~
$ ffmpeg -itsoffset -1 -i P1080893.mov -ss 0.1 -vframes 1 -y P1080893.jpg
ffmpeg version 3.2.8-1~deb9u1 Copyright (c) 2000-2017 the FFmpeg developers
[...]
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
~~~~

When I drop the `-ss 0.1`, it works. I've also got another video where I need to drop both `-ss` and `-itsoffset`.

**Comment by rprieto** [comment]
Thanks for reporting the issue. It should be fixed in https://github.com/thumbsup/downsize/commit/863fcee3e43368a99c660f3b3811dbaec90c8493, I'll publish a new version soon.

In short: it used to extract video stills at `t=1s` to avoid black thumbnails for videos that fade-in. For now I moved it to `t=0.1s`. In your view should it be configurable, or would it be enough to always screenshot `t=duration/2`?

**Comment by tribut** [comment]
Thanks for the follow-up. That should fix the problem with my videos.

I still think it would be better to fail gracefully if a preview cannot be generated, not sure if that's technically bug though 😏

**Comment by rprieto** [comment]
Hi, yes I was looking at #75 which is similar. I just posted an update on that issue. I'll close this issue for now if that's OK with you and release a new version soon.
