### ISSUE TITLE
Cannot handle large quantities of content

### ISSUE THREAD

**Issue by scubachristopher** [thumbsup/thumbsup#84]
## Feature request

Please describe the new feature or behaviour you'd like to see.
If possible, give a concrete use case.

## Bug report

If running as an npm package:

```
Thumbsup version: latest as of Dec 1 2017
Node version: 8.9.1
NPM version: 5.5.1
Operating system: Mac OS-X High Sierra
```

If running as a Docker container:

```
Thumbsup image tag: __________
Docker version: __________
Operating system: __________
```

About the bug...

- Are you getting an error message?
- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?
- Is the behavior different from expected?
- Can you provide steps to reproduce the issue?

NFS mount to NAS from Mac.  8GB RAM, local resources fine

```
Christophers-Macintosh:Pictures Christopher$ thumbsup --input /Volumes/photo/ --output /Volumes/usbshare4/Gallery/ --title "Christopher Yates Family Photos" --theme "cards"


Finding media       [=========================] 38161/38161 done
Updating database   [===========--------------] 16488/38161 (228min left)fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EAGAIN: resource temporarily unavailable, open '/Volumes/usbshare4/Gallery/metadata.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at save (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/database.js:26:6)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/database.js:8:35)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at exiftool.read (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/files.js:65:17)
    at ChildProcess.child.on (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/exiftool.js:63:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
Christophers-Macintosh:Pictures Christopher$
Christophers-Macintosh:Pictures Christopher$ thumbsup --input /Volumes/photo/ --output /Volumes/usbshare4/Gallery/ --title "Christopher Yates Family Photos" --theme "cards"

Finding media       [=========================] 38161/38161 done
Updating database   [===========--------------] 16603/38161 (192min left)fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EAGAIN: resource temporarily unavailable, open '/Volumes/usbshare4/Gallery/metadata.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at save (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/database.js:26:6)
    at EventEmitter.emitter.on (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/database.js:8:35)
    at emitOne (events.js:121:20)
    at EventEmitter.emit (events.js:211:7)
    at exiftool.read (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/files.js:65:17)
    at ChildProcess.child.on (/usr/local/lib/node_modules/thumbsup/node_modules/exiftool-json-db/lib/exiftool.js:63:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
```

**Comment by rprieto** [comment]
Thanks for raising this! Version `2.2.0` is about to be released with many optimisations. Do you mind trying `2.2.0-alpha.3`? There's a known issue with IPTC keywords though, so if you have keywords you'll need to wait until alpha 4 (in the next few days).

**Comment by scubachristopher** [comment]
Yes, I will and will inform.  Am doing a run with debug now.

**Comment by scubachristopher** [comment]
I’ve pulled down the version with the tag.  How do I make this the runnable version on Mac?  I npm’d the original install.

 

                

 

From: Christopher Yates <scubachristopher@gmail.com>
Date: Saturday, December 2, 2017 at 1:14 PM
To: thumbsup/thumbsup <reply@reply.github.com>, thumbsup/thumbsup <thumbsup@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [thumbsup/thumbsup] Cannot handle large quantities of content (#84)

 

 

                Yes, I will and will inform.  Am doing a run with debug now.

**Comment by rprieto** [comment]
If you git cloned the repo, you can run:

```bash
cd /path/to/thumbsup/repo
git checkout master && git pull
npm install
node bin/thumbsup.js --input "../photos" --output "../website"
```

**Comment by scubachristopher** [comment]
Bummer.


Christophers-Macintosh:thumbsup Christopher$ DEBUG="*" node ./bin/thumbsup.js --input /Volumes/photo/ --output /Volumes/usbshare4/Gallery/ --title "Christopher Yates Family Photos" --theme "cards"


 ⠙ Indexing folder
   Resizing media
   Creating website
  snapdragon:compiler initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/compiler.js +0ms
  snapdragon:parser initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/parser.js +12ms
  snapdragon:compiler initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/compiler.js +7ms
  snapdragon:parser initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/parser.js +0ms
  snapdragon:compiler initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/compiler.js +2ms
  snapdragon:parser initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/parser.js +0ms
  snapdragon:compiler initializing /Users/Christopher/thumbsup/thumbsup/node_modules/micromatch/node_modules/snapdragon/lib/compiler.js +2ms
 ⠼ Indexing folder
   → Indexing 19511/38161 (51%)
   Resizing media
   Creating website

/Users/Christopher/thumbsup/thumbsup/src/components/index/index.js:86
        insertStatement.run(entry.SourceFile, timestamp, JSON.stringify(entry))
                        ^
SqliteError: unable to open database file
    at Stream.stream.on.entry (/Users/Christopher/thumbsup/thumbsup/src/components/index/index.js:86:25)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Stream.stream.write (/Users/Christopher/thumbsup/thumbsup/node_modules/event-stream/index.js:61:10)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at Stream.reemit (/Users/Christopher/thumbsup/thumbsup/node_modules/event-stream/node_modules/duplexer/index.js:70:25)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)

**Comment by rprieto** [comment]
Haven't seen that before :( What happens if you run it again? It should pick up where it left off.

I'll have a look see what can cause this. The output is called `usbshare4`, is that a USB drive? I wonder if there was a file system glitch and the indexer should be retrying.

**Comment by scubachristopher** [comment]
Mac to a Synology NAS, photo is the mount point for the source content, the NAS has an external USB drive which is mounted as the destination gallery.

Rebooted and restarted as you suggested and was able to get past indexing -- thank you.  My view is indexer should be retrying.  If your network bounces, ideally, you would inform and just retry until the connection came back up and it continued.

79k pieces of content to chew through, so it will take quite a while.  I'll inform if there are further issues.

Really love this solution -- it's precisely what I was looking for.  So thanks for all of the work and immediate response on the issue.

**Comment by rprieto** [comment]
Thanks for the update, please do let me know. I'll have a look to see how we could implement retry. It should ideally be smart to detect a retryable error vs for example a corrupted image.

I also run a Synology NAS, and am investigating running as a Docker container on the NAS on a schedule. I can update you on how it goes!

**Comment by rprieto** [comment]
Thinking about it, part of the problem is that I assumed the index (`thumbsup.db`) to be local. SQLite might not cope well with making lots of updates over the network. An option could be the ability to customise the index path to somewhere local, like

```bash
--input /mnt/nas/photos
--output /mnt/nas/gallery
--index-path ~/holidays.db 
```

In the meantime, the good thing is that indexing is incremental so
- you can restart if it crashes
- it only makes that many SQLite requests the very first time, and should be more stable for smaller ongoing updates

**Comment by scubachristopher** [comment]
/agreed on both counts.

 

                But I would also continue to suggest a pattern where, after initially ensuring you can connect to all files / directories, once you are “processing” I believe you should retry whatever is failing and inform the user as opposed to bailing.  When content gets this large, as a user, I really don’t want to babysit it.  I just want it to complete or keep trying until I kill.

 

                Just my perspective.  Clearly less volatile if the db is local and a solid solution.

**Comment by rprieto** [comment]
Definitely agree, all crashes are bad crashes! Will see what I can do.

**Comment by scubachristopher** [comment]
Ok an update from the host doing the processing:

❯ Processing media (1271/79177)
 ✔ Indexing folder
 ✔ Indexing folder
 ❯ Processing media (1272/79177)
   ⠹ media/large/2013/03 March/00041.mp4 (92%)
   ✖ media/thumbs/2006/12 December/DSC00311.JPG
     → Error: Error: Command failed: gm convert: Unable to open file (/Volumes/usbshare4/Gallery/media/thumbs/2006/12 December/DSC00311.JPG) [Resource temporarily unavailable].
   ⠹ media/large/2013/03 March/GOPR0002.mp4 (63%)
   ⠹ media/large/2013/03 March/GOPR0001.mp4 (46%)
   Creating website

Unexpected error { Error: Error: Error: Command failed: gm convert: Unable to open file (/Volumes/usbshare4/Gallery/media/thumbs/2006/12 December/DSC00311.JPG) [Resource temporarily unavailable].

    at job.task.then.catch.err (/Users/Christopher/thumbsup/thumbsup/node_modules/listr-work-queue/lib/index.js:50:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  context:
   { files:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        ... 38031 more items ],
     album:
      Album {
        id: 1,
        title: 'Home',
        basename: 'Home',
        files: [],
        albums: [Array],
        depth: 0,
        home: true,
        stats: [Object],
        previews: [Array],
        path: 'index.html',
        url: 'index.html',
        summary: '23 albums, 35108 photos, 3023 videos' } } }
Christophers-Macintosh:thumbsup Christopher$
Christophers-Macintosh:thumbsup Christopher$ DEBUG="*" node ./bin/thumbsup.js --input /Volumes/photo/ --output /Volumes/usbshare4/Gallery/ --title "Christopher Yates Family Photos" --theme "cards"

**Comment by rprieto** [comment]
Thanks and sorry you're facing so many issues. Looks similar to the indexing, which is that `graphicsmagick` failed to process the file from the NAS. Assuming it was a network glitch, the retry logic should fix that.

In the meantime I'll let you know how I go processing a gallery on the Synology itself. Does your Synology support Docker?

**Comment by scubachristopher** [comment]
Yeah, docker image would be a great solution.  I think it does - will check later and inform (in transit to Europe).


   Thanks,
   Chris

**Comment by scubachristopher** [comment]
Just to keep you updated given you've been so responsive:

✔ Indexing folder
 ❯ Processing media (3375/77902)
 ✔ Indexing folder
 ❯ Processing media (3375/77902)...

Progress.  Has continued to run.  I'll re-fire if it barfs on disconnect again.

**Comment by scubachristopher** [comment]
200GB of 1TB processed.  It has barfed a few times over loss of the mount.  Perhaps the solution is to express the mount points as a part of the optional config so if it loses them, it has the info to re-establish and continue...

But please take this as constructive -- I am really happy about this system.

**Comment by rprieto** [comment]
Thanks that's great to hear! Thanks for the suggestions. I'm also getting some good results running a Docker container on my NAS itself, hopefully will publish the Docker image and documentation sometime this week.

**Comment by scubachristopher** [comment]
thumbsup Unsupported file type: unknown

Would be totally boss if you emitted the name of the file that you do not support...

**Comment by rprieto** [comment]
This warning means the file extension was recognised, but `exiftool` could not identify the actual data type (e.g. corrupted JPEG). This should be a warning and the file should be skipped.

Which version are you running? Can you try the latest `2.2.0` with `--log info`? It should say `thumbsup:warn Unknown file type <unknown> for <file/path>`.

**Comment by scubachristopher** [comment]
It completed!  Other issues in terms of file formats, but will research that separately.  Thanks!

**Comment by rprieto** [comment]
That's great to hear!

I added a page on Synology in the documentation: https://thumbsup.github.io/docs/2-installation/synology/. I successfully ran thumbsup on my NAS on an existing gallery of ~5000 photos and videos. It only rebuilt new files as expected. Photos were very quick to process, but videos gave the NAS a hard time by hogging all the CPU. When https://github.com/thumbsup/thumbsup/pull/77 is implemented, it should play nicer by setting `--threads <lower number than the total number of cores>`.

Quick question: if your gallery is public, would you be keen to have a link on the README / website as a showcase? It would be a great showcase given the number of photos! Completely understand if you don't want to.

**Comment by rprieto** [comment]
ps: the next minor version (already on `master`) will have a `--dry-run` option so you can try running it on the NAS without actually generating thumbnails.

```bash
$ thumbsup --input photos --output website --dry-run --log info
# ...
# thumbsup:info Calculated required tasks { sourceFiles: 4, tasks: 8 }
# thumbsup:info Resizing media [skipped]
# thumbsup:info Creating website [skipped]
```

**Comment by scubachristopher** [comment]
Hi,

 

                So it’s open for now but I’m going to implement basic auth for the site as it’s my family photos.  Check it out:  www.scubachristopher.com.

 

                I ran with the original-images option to get the original content available.  That was cool and worked.

 

                What does original videos do?

**Comment by rprieto** [comment]
`--original-photos` used to control what happens when you click "download" when viewing a photo, or right click on the thumbnail and "save target as".

- if false, it downloads the web-friendly size
- if true, it downloads the original (which is copied into the target folder)

`--original-videos` is exactly the same but for videos.

They are deprecated though in favour of the more flexible `--download-photos` and `--download-videos` options which are documented on https://thumbsup.github.io/docs

**Comment by rprieto** [comment]
PS: I can't see the gallery on the site
