### ISSUE TITLE
thumbnail are rebuild with new version

### ISSUE THREAD

**Issue by eephyne** [thumbsup/thumbsup#85]
version 2.2.0-alpha-3 git version (iptc-keyword branch)

After some issue (previously solved :), When I launch thumbsup it redo all the thumbnails, you assumed this is related to date but I don't know why since nothing change.

Its not a killing bug but since it make a couple of days to generate all the videos its not really nice either.
Its running right now (1695/16000) so if you want me to test something, just ask for it :)

**Comment by rprieto** [comment]
To make sure i understand, you ran `thumbsup ` and it generated all thumbnails and HTML pages, and when you run it again it starts rebuilding all thumbnails again?

If you don't mind troubleshooting, the "date" check is done in `step-process.js` line 38. You could add an extra debugging statement:

```js
console.log(`
  source=${f.path}
  source date=${f.date}
  thumb=${f.output[out].path}
  thumb date=${destDate}
  -----`)
if (action && f.date > destDate) {
```

On first run, `thumb date` should be zero. After that it should be a number greater than the source date.

**Comment by rprieto** [comment]
ps: when `2.2.0` is out I'll add a better verbose logging system to make troubleshooting errors easier!

**Comment by eephyne** [comment]
Well it generate it again only the files that was here before 2.2.0-alpha.
And I did make a mistake moving instead of copying the old files because they're all gone hehe …
It seem running thumbsup deleted the files already present. I'll try something since I got also 2.1.0 installed globally.

**Comment by rprieto** [comment]
One thing that changes between 2.1.0 and 2.2.0 is the index format. Are you sure it's re-building the thumbnails and not just re-indexing?

**Comment by eephyne** [comment]
I just tested a directory with 2.1.0 then 2.2.0-alpha and it does'nt redo the thumbnails, I don't understand what happened.
And yes it regenerate everything

**Comment by rprieto** [comment]
Thinking of possible causes to rule out:
- you mentioned moving files, did the paths in the source folder changed at all? For example if `IMG_0001.jpg` becomes `photos/IMG_0001.jpg` then thumbsup treats it as a deleted/new file and recreated the thumbnail. It doesn't care about absolute paths, as long as the relative path within `--input` always stays the same.
- did you copy the source files somewhere else, before re-running thumbsup? Depending on your OS copying files might change `mtime` in which case it will think all photos have been updated (and thumbnails are out of date)

**Comment by eephyne** [comment]
I never moved the source file, only the output files.
What I did
Upgraded.
Update the folder.
Notify that it rebuild everything
Remove everything except media folder and thumbs.db
Retry, same result.
Delete thumbs.db and retry. Same result.
I tried different flag and I was thinking that maybe --clean deleted the old files since I don't found them anywhere

**Comment by rprieto** [comment]
Hi  @eephyne, sorry I can’t think of an explanation. It might have been because of the database format change. The latest version has **a lot** more debug info in the log (using `--log debug` or `--log trace`), let me know if it happens again!
