### ISSUE TITLE
Sorting by EXIF date?

### ISSUE THREAD

**Issue by ened** [thumbsup/thumbsup#87]
## Feature request

Please allow sorting by EXIF CreateDate.

I am trying to consolidate a few sources of photos and the most meaningful way to handle that is by looking inside the metadata, then sorting based on that.

**Comment by rprieto** [comment]
Hi, thanks for raising an issue. The default behaviour should actually be sorting by date already. This is controlled by the following options:

```
--sort-albums-by         How to sort albums  [choices: "title", "start-date", "end-date"] [default: "start-date"]
--sort-albums-direction  Album sorting direction  [choices: "asc", "desc"] [default: "asc"]
--sort-media-by          How to sort photos and videos  [choices: "filename", "date"] [default: "date"]
--sort-media-direction   Media sorting direction  [choices: "asc", "desc"] [default: "asc"]
```

It uses the EXIF date if available, and falls back to the file modification date otherwise. Do you have an example where it didn't sort as expected?

**Comment by ened** [comment]
Ok, thank you. Seems like my data is unexpectedly incorrect. Will re-open if needed.

**Comment by rprieto** [comment]
No problem. I forgot to mention one of the fallback mechanisms that might be relevant here:
- the date is read from the EXIF date
- if not present, it tries to interpret a date from the filename (e.g. `2016-10-27 09-31-00.jpg`)
- otherwise, it uses the file modification date
