### ISSUE TITLE
tini-related failure with Docker image

### ISSUE THREAD

**Issue by cklempay** [thumbsup/thumbsup#88]
## Bug report

If running as a Docker container:

```
Thumbsup image tag: thumbsupgallery/thumbsup:latest (2.2.1 at the moment)
Docker version: Tried 17.12.0-ce on Windows 10 Pro and 17.05.0-ce on a Synology 218+
Operating system: Win10 Pro, DSM 6.1.4-15217 update 5
```

About the bug...

- Are you getting an error message?

Every attempt to run thumbsup as a container bombs with this error message:

`[FATAL tini(I have seen 5 and 6 here)] exec -v failed: No such file or directory`

- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?

I tried adding a --log trace to the command line, but there was no change in output.

- Is the behavior different from expected?

Yes

- Can you provide steps to reproduce the issue?

A simple Synology example: I have existing images at /volume1/web/album, and want the new gallery to be at /volume1/web/newalbum.

I am running via command line

`sudo docker run thumbsupgallery/thumbsup -v /volume1/web/album:/photos -v /volume1/web/newalbum:/output --input /photos --output /output --title "Legacy Photos"`

**Comment by cklempay** [comment]
Blatant user error here (missing some of the required command line, per the site's docs).  Apologies!

**Comment by rprieto** [comment]
No problem, I hope it all works well now.
