### ISSUE TITLE
Feature request: a configurable parameter for GraphicsMagick

### ISSUE THREAD

**Issue by aellwein** [thumbsup/thumbsup#89]
## Feature request

It would be nice to have a configuration option for a parameter to pass to GraphicsMagick. In my use case, i want to sharpen the image upon "convert", so a "-sharpen" parameter would be the case.

**Comment by rprieto** [comment]
Thanks for the suggestion! I was wondering about output filters in general (e.g. #79). What's your thoughts on having built-in modules (similar to http://sigal.saimon.org/en/latest/plugins.html), or simply allowing full access to the CLI options?

**Comment by aellwein** [comment]
Of course, it would be awesome to have some kind of high level API/plugins over GM filters, as for me, the simple access to CLI option would be enough.

**Comment by aellwein** [comment]
Cool! Thank you.
My current ugly workaround is to patch index.js in thumbsup/downsize in my local node_modules, like so:
```diff
diff --git a/node_modules/thumbsup-downsize/lib/index.js b/node_modules/thumbsup-downsize/lib/index.js
index 5a5638b..510a44b 100644
--- a/node_modules/thumbsup-downsize/lib/index.js
+++ b/node_modules/thumbsup-downsize/lib/index.js
@@ -27,7 +27,8 @@ exports.image = function (source, target, options, callback) {
     image.resize(null, options.width, '>')
   }
   // default quality, for typical web-friendly sizes
-  image.quality(options.quality || 90)
+  image.quality(options.quality || 98)
+  image.unsharp(2, 0.5, 0.7, 0)
   // write the output image
   image.write(target, callback)
 }
```
But i will definitely try the '--gm-args' option out, thanks for support.

**Comment by rprieto** [comment]
That's great. Anoher option is to simply allow:

`--gm-plugin ./image.js`

```js
// image.js
module.exports = (image, path, width, height) => {
  image.unsharp(2, 0.5, 0.7, 0)
}
```

Then you could use the GM library as you like, including adding logic like:

```js
// add a watermark to large images
if (width > 500) {
    image.subCommand('composite')
    image.in('-compose', 'Over', 'watermark.png')
}
```

**Comment by rprieto** [comment]
Hi @aellwein, can you give version `2.3.1` a try? You should be able to specify:

```bash
thumbsup --input photos --output gallery --gm-args 'unsharp 2 0.5 0.7 0'
```

**Comment by aellwein** [comment]
@rprieto, it works pretty well,
i even tried it with the "gm-args" option in my config.json, works like a charm.
Unfortunately, i've run into [this issue](https://github.com/JoshuaWise/better-sqlite3/issues/130) while building better-sqlite3 on my Arch machine, but using the described workaround i've managed to install and test everything with the newest Node.js. Thanks!
