### ISSUE TITLE
Manually adjust parallelism

### ISSUE THREAD

**Issue by bglopez** [thumbsup/thumbsup#91]
## Feature request

As a user I would like to be able to manually adjust the indexing paralellism using an argument passed to the application. I see that currently it is set via enumerating the max cores of the system it runs on in https://github.com/thumbsup/thumbsup/blob/cd3d699b34005297bcec66b3666c2296e73f5cc7/src/steps/step-process.js#L14

Possibly some option like `--concurrency N` where N is the number of concurrent processing threads, could be be made available.

**Comment by bglopez** [comment]
#92 opened, I've done the work to add this.

**Comment by rprieto** [comment]
Hi, thanks a lot for that. This would solve #77. I'll take a look at the PR now.

**Comment by rprieto** [comment]
Thanks, I've merged #92.
