### ISSUE TITLE
Fails silently if exiftool isn't installed

### ISSUE THREAD

**Issue by orezpraw** [thumbsup/thumbsup#95]
If exiftool isn't installed the only output on running thumbsup is

Gallery generated successfully
1 albums, 0 photos, 0 videos

**Comment by rprieto** [comment]
Thanks, I agree if would be great to have startup checks for exiftool, ffmpeg and graphicsmagick.

**Comment by rprieto** [comment]
The following packages look great:
https://www.npmjs.com/package/bin-exists
https://www.npmjs.com/package/command-exists
