### ISSUE TITLE
Custom themes update?

### ISSUE THREAD

**Issue by chrisssycollins** [thumbsup/thumbsup#97]
Thumbsup is amazing! Been messing around for about 30 mins and I'm hooked. I currently have a Jekyll workflow for my static photo gallery but I am very interested in Thumbsup!

I'm a UX/UI designer and developer and would love to be able to design and create themes and release them for all to use.

Any updates on the progress?

**Comment by rprieto** [comment]
Hi @chrisssycollins. The latest code on `master` allows you to load a theme from an arbitrary path using `--theme-path ./my/theme`. I updated the documentation at https://thumbsup.github.io/docs/4-themes/themes/. Do you want to take a look before I release the new version?

**Comment by chrisssycollins** [comment]
Hey @rprieto. I'll have a try at throwing together a basic theme, bare with me 👍.

**Comment by chrisssycollins** [comment]
Hey @rprieto,

I have put together a very basic theme, you can [view a demo](https://chrisssycollins.github.io/mylo-thumbsup-theme) or view the [source](https://github.com/chrisssycollins/mylo-thumbsup-theme).

The theme is pretty barebones, this is deliberate. It uses [tailwindCSS](https://tailwindcss.com/) and I have not used any helpers or partials for the time being. 

Next steps would be to use this as a base for me to create a theming workflow/build around it which will handle optimising etc. I still believe, for the time being, all theme builds and maintaining themes should be kept outside of the thumbsup core and users would only use compiled themes in thumbsup. 

Overall, pretty easy to implement. More than happy to work with you to get the theming side of things off the ground.

**Comment by chrisssycollins** [comment]
Right now there are 3 themes bundled in the codebase. In your opinion should they have their own repo, to set a good example for custom themes?
> Yes, then most people will use them as a standalone starting point and they can be maintained outside the core. 

Should thumbsup bundle any JS frameworks like LightGallery and VideoJS (it currently does), or should it really be up to the theme to do their own thing? (I see your theme bundles them too)
> No, I think these should be per theme to allow the frontend developer to add a lightbox/libs of their choice. This also means thumbsup isn't responsible for updating frontend dependencies and any breaking changes they may have, which is a good thing imo. 

I really like how the photos in your theme resize based on the window size, and aren’t always square. Should thumbsup move away from square thumbnails, and instead keep the original ratio and let the theme display however it wants?
> I like the square thumbnails but yes I think using the correct aspect ratio gives developers the option to create [masonry style layouts](https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/twofold-creative-masonry-website-template.jpg) or a [Flickr style layout](https://librisblog.photoshelter.com/wp-content/uploads/2015/07/Explore___Flickr_-_Photo_Sharing_.png).  

Happy to move the theme across to the organisation and happy to help.

Looking forward to seeing the community grow 😃.

**Comment by rprieto** [comment]
Hi @chrisssycollins, all themes have now been extracted from Thumbsup core: 

- https://github.com/thumbsup/theme-cards
- https://github.com/thumbsup/theme-mosaic
- https://github.com/thumbsup/theme-classic

You can look at the structure and the updated docs for details. Let me know if you need any help finalising your theme!

**Comment by chrisssycollins** [comment]
Hey @rprieto I just got married and going on my honeymoon for a week, will pick this up when I am back.
